"""Which documents are publishable, and how they are made safe to publish.

ONE registry, TWO published surfaces
------------------------------------
The same Markdown in ``docs/`` reaches three places:

* the repository itself — the copy the team edits, unredacted;
* the static site (``site/docs/*.html``), generated by
  ``deploy/gen_site_docs.py`` and served on the public web;
* the application itself, **without a session**, at ``/docs/public`` — so an
  operator standing at a sign-in screen on an isolated management network can
  read the manual with no account and no internet.

Both PUBLISHED surfaces have to agree on what may be published and on what is
rewritten before it is. While that list and the redaction table lived inside
the site generator, the application could not reuse them, and the application
grew its own unredacted public route: ``/docs/api`` served ``docs/api_v1.md``
verbatim, disclosing a management hostname and an RFC1918 address to anyone who
could reach the login page. A second copy is the copy that rots — so the
registry lives here and both surfaces import it.

REDACTION IS NOT OPTIONAL
-------------------------
Eleven of the shipped documents carry real internal identifiers: RFC1918
addresses, management hostnames, hypervisor and node names, the backup server
and an administrator's e-mail. Publishing them verbatim is an inventory
disclosure.

Two passes, in this order:

1. :func:`redact` rewrites known internal identifiers to ``{placeholder}``
   tokens, so the published text still reads as documentation.
2. :func:`scan` re-checks the OUTPUT. The site generator aborts the whole run
   on a hit; the application refuses to serve the page. Neither warns and
   continues — a warning in a publication path is a leak with a paper trail.

Placeholders use ``{braces}``, never ``<angle brackets>``: an ``<ip>`` written
into HTML is parsed as an unknown ELEMENT and renders as nothing at all, so the
sentence silently loses a word. An invisible redaction is worse than an obvious
one, and ``{...}`` already means "substitute me" everywhere else in this repo.

Device SHORT names (``fadc``, ``faz``, ``fortiweb``) are deliberately NOT
redacted — they are ADOM keys and URL segments of the product itself
(``/fadc/api/``); rewriting them would mangle route documentation while
disclosing nothing. A label with no address is not an inventory.

This module is deliberately stdlib-only and imports nothing from ``app``: the
site generator has to keep working on a tree whose application code does not
even compile (that has happened — see the ``cert_service`` entry in the
changelog), and a documentation build that needs a healthy app to tell you the
app is broken is worth nothing.
"""
from __future__ import annotations

import json
import pathlib
import re

ROOT_DIR = pathlib.Path(__file__).resolve().parents[2]
DOCS_DIR = ROOT_DIR / "docs"

# ---------------------------------------------------------------------------
# What gets published, in reading order. A doc absent from this list is simply
# not published anywhere public — that absence IS the opt-in.
# Tuple: (markdown file, output slug, title, icon, blurb)
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# Where the manual actually lives.
#
# The application does not serve documentation. Every in-product link points
# here, so the address exists once: a literal in two templates is two chances
# to move the site and leave one of them pointing at a 404.
# ---------------------------------------------------------------------------
SITE_BASE = "https://satom.visionebc.com"


def site_url(slug: str | None = None) -> str:
    """Public URL for the hub, or for one published document."""
    if not slug:
        return f"{SITE_BASE}/docs.html"
    return f"{SITE_BASE}/docs/{slug}.html"


PUBLIC_DOCS: list[tuple[str, str, str, str, str]] = [
    ("README.md", "readme", "How to read this manual", "\U0001f5fa️",
     "The map: every document, which one to read for which job, and the rules that keep the manual honest."),
    ("CHANGELOG.md", "changelog", "Changelog", "\U0001f5d2️",
     "Every release and every change, newest first — the same file that ships in the repository and is readable inside the application."),
    ("management-overview.md", "management-overview", "Management overview", "\U0001f9ed",
     "The system without jargon: what it solves, how mature it is, what it costs and what the risks are."),
    ("overview.md", "overview", "Project overview & operating rules", "\U0001f4cc",
     "What the platform is, how it is deployed, its security posture, and the rules the team works by."),
    ("user-guide.md", "user-guide", "User guide", "\U0001f4d6",
     "Day-to-day operation, screen by screen — the manual for someone using the web interface."),
    ("INSTALL.md", "install", "Installation & deployment", "\U0001f4e6",
     "Requirements, package lists per distribution, the preflight, clustering, hardening and uninstall."),
    ("cli.md", "cli", "Operator console (satom CLI)", "⌨️",
     "The command-line tool for a node whose web interface is down: diagnose, control, rebuild — and the sudo rule to request."),
    ("theming.md", "theming", "Theming the console", "\U0001f3a8",
     "Design tokens, named themes, the value allowlist that keeps operator input out of the "
     "stylesheet's structure, the contrast audit and how to get back."),
    ("privilege-model.md", "privilege-model", "Privilege model & node trust", "\U0001f510",
     "Which account runs what, the two-command sudo allowlist, the privileged-runner boundary and node-to-node trust."),
    ("safeguards.md", "safeguards", "Safeguards — full catalog", "\U0001f6e1️",
     "Every protection: what it prevents, where it lives, and the command that proves it is armed."),
    ("offline-update-packages.md", "offline-update-packages",
     "Offline update packages", "\U0001f4e5",
     "Update a node with no route to the git remote: signed packages, the trust "
     "store that decides which signatures count, preflight, and the privileged "
     "apply with automatic rollback."),
    ("metrics-architecture.md", "metrics-architecture",
     "Metrics & the device source of truth", "\U0001f4c8",
     "Where operational data lives and why: the fleet-scale measurement, "
     "aggregated collection, the time-series store, selector dashboards, "
     "reports, and the content-addressed source-of-truth store that replaced "
     "the git-committed history."),
    ("git-backup-and-outage.md", "git-backup", "Git backup & surviving an outage", "\U0001f9ef",
     "The anti-reset guard, the unpushed-commit alert, repository bundles and the four-copy recovery runbook."),
    ("encryption-and-node-tls.md", "encryption", "Encryption in transit & node TLS", "\U0001f512",
     "Service certificates, node-to-node encryption, enforced database TLS and the live encryption probes."),
    ("acme-certificate-manager.md", "acme", "ACME / Let's Encrypt certificates", "\U0001f4dc",
     "Automated issuance, the DNS-provider catalog, and how credentials reach the signer without leaking."),
    ("api_v1.md", "api", "API v1 — integration manual", "\U0001f50c",
     "How a third party authenticates and drives the platform with a token."),
    ("device-api.md", "device-api", "Device APIs & the endpoint registry", "\U0001f52d",
     "The API consoles that drive the appliances, and the registry that makes a moved firmware URI a row edit instead of a release."),
    ("fortiauthenticator.md", "fortiauthenticator",
     "FortiAuthenticator — product integration", "\U0001f194",
     "How the identity product is wired: its Tastypie REST dialect, the "
     "per-user API key, the pagination trap and the 18-character ADOM ceiling "
     "it exposed."),
    ("engineering.md", "engineering", "Engineering manual", "\U0001f3d7️",
     "Internal architecture for developers: layers, the endpoint registry, device clients, jobs and testing."),
    ("source-of-truth-spec.md", "source-of-truth", "Source-of-truth specification", "\U0001f5c2️",
     "The authoritative behavioural specification for configuration harvesting and versioning."),
    ("release-pipeline.md", "release-pipeline", "Release & publication pipeline", "\U0001f69a",
     "How a release is sanitized, secret-scanned, audited and published."),
    ("release_notes.md", "release-notes", "Appliance upgrade advisor \u2014 vendor notes", "\U0001f4cb",
     "The FORTINET known/resolved issue corpus behind the upgrade advisor \u2014 "
     "not SATOM's own release history, which is the Release notes section."),
    ("server_policy.md", "server-policy", "Server policy reference", "\U0001f9f1",
     "Field-level reference for the server policy object graph."),
    ("web_protection_profile.md", "web-protection-profile", "Web protection profile reference", "\U0001f9ec",
     "The ~40 sub-policy WAF bundle, field by field."),
    ("wpp_exceptions.md", "wpp-exceptions", "WAF exceptions & signatures", "\U0001fa79",
     "Authoring and injecting WAF exceptions and signature carve-outs."),
    ("fortiadc.md", "fortiadc", "FortiADC — API conventions", "\U0001f9fe",
     "REST conventions, object map and current coverage for FortiADC."),
]

GROUPS: list[tuple[str, str, list[str]]] = [
    ("Start here", "New to the platform — read these in order.",
     ["readme", "management-overview", "overview", "user-guide", "theming"]),
    ("Deploy & operate", "Getting it running, keeping it running, getting it back.",
     ["install", "cli", "privilege-model", "safeguards", "metrics-architecture",
      "git-backup", "offline-update-packages"]),
    ("Security", "Certificates, transport encryption and trust between nodes.",
     ["encryption", "acme"]),
    ("Build & integrate", "For developers extending the platform or driving it from outside.",
     ["api", "device-api", "fortiauthenticator", "engineering",
      "source-of-truth", "release-pipeline",
      "release-notes"]),
    ("What changed", "Release history for the platform itself.",
     ["changelog"]),
    ("Device reference", "Field-level reference for the managed appliances.",
     ["server-policy", "web-protection-profile", "wpp-exceptions", "fortiadc"]),
]

# ---------------------------------------------------------------------------
# Redaction — ORDER MATTERS: specific identifiers before the generic patterns.
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# Site-specific names live OUTSIDE the source tree.
#
# A rule table that names the estate it protects is itself the disclosure. And
# it hid behind its own escaping. A rule written `\bNAME\b` contains, as
# TEXT, the letter b immediately before NAME -- so a \b-anchored redaction
# rule cannot match its own escaped form, and a \b-anchored scanner cannot
# flag it either. Both agreed, both were wrong, and the names rode out to the
# public mirror inside the very module that exists to stop them.
#
# What stays in code is generic and always fires: address ranges and personal
# e-mail. What identifies THIS deployment -- node names, hypervisors, the
# backup host, the management domain -- is read from an untracked overlay next
# to the application. Absent (a published mirror, a fresh install), the generic
# rules still apply, and there is nothing site-specific left to redact anyway.
#
# The internal suite asserts the overlay is present, so a node that loses it
# fails loudly instead of quietly redacting less.
OVERLAY_PATH = ROOT_DIR / "publication-rules.local.json"


def _load_overlay() -> dict:
    try:
        return json.loads(OVERLAY_PATH.read_text(encoding="utf-8"))
    except (FileNotFoundError, ValueError):
        return {}


_OVERLAY = _load_overlay()


def _overlay_rules(key: str) -> list[tuple[re.Pattern, str]]:
    out = []
    for entry in _OVERLAY.get(key, []):
        try:
            out.append((re.compile(entry["pattern"]), entry["replacement"]))
        except (KeyError, re.error):
            continue
    return out


def _overlay_forbidden() -> list[tuple[str, re.Pattern]]:
    out = []
    for entry in _OVERLAY.get("forbidden", []):
        try:
            out.append((entry["name"], re.compile(entry["pattern"])))
        except (KeyError, re.error):
            continue
    return out


REDACTIONS: list[tuple[re.Pattern, str]] = [
    # Trailing [a-z0-9]* not + : a bare prefix ("satom-node") is still an
    # identifier, and requiring a suffix is the same anchoring mistake the
    # hostname rule made with wildcards. Caught on a LIVE served page.
    # Anchored on the DOMAIN, not the leading label: real documentation writes
    # wildcard certs (*.example.net) and brace expansions (satom{,-2}.example.net),
    # neither of which starts with an alphanumeric. A label-anchored pattern
    # matched neither and the scanner caught all four occurrences.
    # "192.0.2.248/.249" — a shorthand pair. The generic IP rule below rewrites
    # the first and leaves "/.249", which still discloses an octet.
    (re.compile(r"\b10\.\d{1,3}\.\d{1,3}\.\d{1,3}/\.\d{1,3}\b"), "{ip}/{ip}"),
    (re.compile(r"\b[A-Za-z0-9._%+-]+@(?:gmail|hotmail|outlook|yahoo)\.[A-Za-z]{2,}\b"),
     "{admin@example.net}"),
    (re.compile(r"\b10\.\d{1,3}\.\d{1,3}\.\d{1,3}\b"), "{ip}"),
    (re.compile(r"\b192\.168\.\d{1,3}\.\d{1,3}\b"), "{ip}"),
    (re.compile(r"\b172\.(?:1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3}\b"), "{ip}"),
] + _overlay_rules("redactions")

# Re-checked against the OUTPUT. A hit aborts the site build and makes the
# application refuse to serve the page.
FORBIDDEN: list[tuple[str, re.Pattern]] = [
    ("rfc1918 address", re.compile(r"\b(?:10\.\d{1,3}|192\.168|172\.(?:1[6-9]|2\d|3[01]))\.\d{1,3}\.\d{1,3}\b")),
    ("personal e-mail", re.compile(r"[A-Za-z0-9._%+-]+@(?:gmail|hotmail|outlook|yahoo)\.")),
] + _overlay_forbidden()

# The published renderer does NOT use nl2br: these files are hard-wrapped at
# ~90 columns and nl2br turns every wrap into a visible line break.
MD_EXTENSIONS = ["toc", "fenced_code", "tables", "sane_lists", "attr_list"]


# ---------------------------------------------------------------------------
# Cross-references between documents.
#
# The manual is written as Markdown that links to Markdown: `[the CLI](cli.md)`.
# That is correct in the repository and DEAD everywhere it is published, because
# the published artefact is `cli.html` and nothing serves the `.md`. The links
# rendered fine, returned 200 on the page that contained them, and every one of
# them 404ed when followed — 71 of them across 10 pages, found only by
# requesting a target.
#
# So the filename -> slug map that decides what gets published also decides
# what a cross-reference is rewritten to. A link to a document that is NOT
# published cannot be made to work, so it is unwrapped to plain text rather
# than shipped as a link that lies.
# ---------------------------------------------------------------------------
SLUG_BY_FILE: dict[str, str] = {md_name: slug for md_name, slug, *_ in PUBLIC_DOCS}

# href="cli.md" / href="./cli.md" / href="docs/cli.md" / href="cli.md#section"
_MD_HREF = re.compile(
    r'href="(?:\./)?(?:[^"#]*/)?([A-Za-z0-9_.\-]+\.md)(#[^"]*)?"')
# Whatever survives the rewrite is a link to something unpublished.
_DEAD_ANCHOR = re.compile(
    r'<a\b[^>]*href="[^"]*\.md(?:#[^"]*)?"[^>]*>(.*?)</a>', re.DOTALL)


def relink(body_html: str) -> str:
    """Rewrite inter-document Markdown links to their published slugs."""
    def _to_slug(m: re.Match) -> str:
        filename, fragment = m.group(1), m.group(2) or ""
        slug = SLUG_BY_FILE.get(filename)
        if slug is None:
            return m.group(0)  # unpublished — unwrapped below
        return f'href="{slug}.html{fragment}"'

    body_html = _MD_HREF.sub(_to_slug, body_html)
    # A link that cannot resolve is downgraded to its own text: the sentence
    # still reads, and nothing invites a click that 404s.
    return _DEAD_ANCHOR.sub(lambda m: m.group(1), body_html)


def redact(text: str) -> str:
    for pattern, replacement in REDACTIONS:
        text = pattern.sub(replacement, text)
    return text


def scan(text: str, where: str) -> list[str]:
    findings = []
    for lineno, line in enumerate(text.splitlines(), 1):
        for name, pattern in FORBIDDEN:
            m = pattern.search(line)
            if m:
                findings.append(f"{where}:{lineno}: {name}: {m.group(0)!r}")
    return findings


def source_for(md_name: str) -> pathlib.Path:
    """Where a published document actually lives.

    Most sit in ``docs/``. The changelog sits at the repo root because that is
    where every other tool looks for it (Keep a Changelog, the forge, the
    release pipeline); copying it into ``docs/`` would create a second copy
    that rots. One resolver, so the presence check and the renderer cannot
    disagree about which files exist.
    """
    in_docs = DOCS_DIR / md_name
    return in_docs if in_docs.is_file() else ROOT_DIR / md_name


def by_slug() -> dict[str, tuple[str, str, str, str, str]]:
    return {slug: entry for entry in PUBLIC_DOCS for slug in (entry[1],)}


def grouped() -> list[dict]:
    """The hub layout: groups, each carrying its resolved document entries."""
    index = by_slug()
    out: list[dict] = []
    for name, lead, slugs in GROUPS:
        docs = []
        for slug in slugs:
            md_name, _slug, title, icon, blurb = index[slug]
            docs.append({"slug": slug, "title": title, "icon": icon,
                         "blurb": blurb, "source": md_name})
        out.append({"name": name, "lead": lead, "docs": docs})
    return out
