"""FortiAnalyzer sidebar menu — the REAL FAZ 7.6.7 GUI panes, verbatim.

Source of truth: the FortiAnalyzer 7.6.7 Administration Guide "GUI overview"
(doc 537284) crawled through the fleet Firecrawl on 2026-07-12 — the left
navigation of the real unit is Device Manager / FortiView / Log View /
Fabric View / Incidents & Events / FortiAI / Reports / System Settings, and
each group's items below mirror that pane's tree menu (the guide's chapter
tree). This file must NOT invent groupings: when the GUI gains or moves a
pane on an upgrade, re-crawl the guide and mirror it here.

Every leaf carries ``logicals``: (registry_name, tab_label) pairs resolved
through ``registry.loader.resolve_faz`` and fetched live by
:func:`app.views.faz.menu_page` via JSON-RPC. Leaves whose GUI feature has
NO JSON-RPC surface on 7.6.7 (probed live on faz01 — event handlers,
playbooks, SIEM parsers, subnets, logging topology, per-unit event log,
FortiView drilldowns) keep an EMPTY ``logicals`` tuple: the page renders the
honest "no endpoint bound" state instead of fake data. Renaming an URI on a
FAZ upgrade is a Registry-page edit, never a code change (same contract as
FortiWeb/FortiADC). The Fleet and Administration areas are NOT here — they
reuse the real shared blueprints and are hardcoded in the sidebar, exactly
like FortiADC.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Item:
    key: str
    label: str
    icon: str = 'bi-dot'
    desc: str = ''
    # (registry logical name, tab label) pairs — live tabs on the section page.
    logicals: tuple = field(default=())


@dataclass(frozen=True)
class Group:
    key: str
    label: str
    icon: str
    items: tuple


_MENU = (
    Group('device-manager', 'Device Manager', 'bi-hdd-rack', (
        Item('devices', 'Devices & Groups', 'bi-router',
             'Devices registered to send logs (authorized and unauthorized are '
             'flagged in the same table) and the device groups that organize them.',
             (('dvmdb_device', 'Devices'), ('dvmdb_group', 'Device Groups'))),
    )),
    Group('fortiview', 'FortiView', 'bi-bar-chart-steps', (
        Item('fortiview-monitors', 'FortiView & Monitors', 'bi-graph-up',
             'FortiView / Monitors dashboards are session-driven drilldowns the '
             'JSON-RPC API does not expose as plain lists on 7.6.7 — use the '
             'unit GUI for the dashboards; their settings are editable here.',
             (('system_fortiview_setting', 'Settings'),
              ('report_est_browse_time', 'Est. browse time'))),
    )),
    Group('log-view', 'Log View', 'bi-journal-text', (
        Item('logs', 'Logs', 'bi-card-list',
             'Logging pipeline state: per-device log rates and the log fields '
             'known to the SQL database.',
             (('logview_logstats', 'Log stats'),
              ('logview_logfields', 'Log fields'))),
        Item('log-browse', 'Log Browse', 'bi-archive',
             'Current and rolled log files on the unit, per device.',
             (('logview_logfiles', 'Log files'),)),
        Item('log-groups', 'Log Groups', 'bi-collection',
             'Log groups are a GUI/ADOM feature with no JSON-RPC list on '
             '7.6.7 (probed live).'),
    )),
    Group('fabric-view', 'Fabric View', 'bi-diagram-3', (
        Item('assets', 'Asset Identity Center', 'bi-pc-display',
             'User and entity behavior analytics (UEBA): endpoints and end users '
             'learned from logs.',
             (('ueba_endpoints', 'Assets'), ('ueba_endusers', 'Identities'))),
        Item('subnets', 'Subnets', 'bi-bounding-box',
             'Subnet definitions are a GUI feature with no JSON-RPC list on '
             '7.6.7 (probed live).'),
    )),
    Group('incidents-events', 'Incidents & Events', 'bi-exclamation-octagon', (
        Item('incidents', 'Incidents', 'bi-clipboard-pulse',
             'SOC incidents raised from events.',
             (('incidentmgmt_incidents', 'Incidents'),)),
        Item('event-monitor', 'Event Monitor', 'bi-activity',
             'Alerts generated by event handlers, and their per-alert logs.',
             (('eventmgmt_alerts', 'Alerts'),
              ('eventmgmt_alertlogs', 'Alert logs'))),
        Item('event-handlers', 'Event Handlers', 'bi-lightning-charge',
             'Basic/correlation event handlers are managed in the unit GUI — '
             '7.6.7 exposes no JSON-RPC list for them (probed live).'),
        Item('automation', 'Automation', 'bi-gear-wide-connected',
             'Playbooks and fabric connectors (SOC Automation subscription) '
             'have no JSON-RPC list on 7.6.7 (probed live).'),
        Item('siem-parsers', 'SIEM Log Parsers', 'bi-braces',
             'SIEM log parsers are managed in the unit GUI — no JSON-RPC list '
             'on 7.6.7 (probed live).'),
        Item('ie-fortiguard', 'FortiGuard Services', 'bi-shield-check',
             'Outbreak alert / IOC service state as seen by the update service.',
             (('fmupdate_service', 'Services'),
              ('fmupdate_publicnetwork', 'Public network'),
              ('fmupdate_server_access_priorities', 'Server access'))),
    )),
    Group('fortiai', 'FortiAI', 'bi-stars', (
        Item('fortiai-assistant', 'FortiAI Assistant', 'bi-robot',
             'The FortiAI assistant requires a FortiAI license and runs inside '
             'the unit GUI; it has no JSON-RPC surface on 7.6.7.'),
    )),
    Group('reports', 'Reports', 'bi-file-earmark-bar-graph', (
        Item('generated-reports', 'Generated Reports', 'bi-file-earmark-check',
             'Reports generated in the last 30 days.',
             (('report_generated', 'Generated'),)),
        Item('report-definitions', 'Report Definitions', 'bi-files',
             'Report layouts and the chart / macro / dataset libraries they '
             'are built from.',
             (('report_layouts', 'All Reports'), ('report_charts', 'Chart Library'),
              ('report_macros', 'Macro Library'), ('report_datasets', 'Datasets'))),
        Item('report-advanced', 'Advanced', 'bi-sliders2',
             'Report schedules, languages and output profiles.',
             (('report_schedules', 'Schedules'), ('report_languages', 'Languages'),
              ('report_outputs', 'Output profiles'))),
    )),
    Group('system-settings', 'System Settings', 'bi-gear', (
        Item('logging-topology', 'Logging Topology', 'bi-share',
             'The logging topology map is a GUI visualization; its underlying '
             'device list lives in Device Manager.'),
        Item('network', 'Network', 'bi-hdd-network',
             'Management interfaces, static routes and DNS of the unit.',
             (('system_interface', 'Interfaces'), ('system_route', 'Routes'),
              ('system_dns', 'DNS'))),
        Item('adoms', 'Administrative Domains', 'bi-collection',
             'Administrative domains defined on the unit (per-product log buckets).',
             (('dvmdb_adom', 'ADOMs'),)),
        Item('fabric-management', 'Fabric Management', 'bi-bezier2',
             'FortiAnalyzer Fabric (SOC fabric) supervisor/member configuration.',
             (('system_soc_fabric', 'SOC fabric'),)),
        Item('certificates', 'Certificates', 'bi-shield-lock',
             'Local, CA, CRL and remote certificates used by the unit services. '
             'Import/generate is an upload operation done in the unit GUI.',
             (('system_certificate_local', 'Local'), ('system_certificate_ca', 'CA'),
              ('system_certificate_crl', 'CRL'),
              ('system_certificate_remote', 'Remote'),
              ('system_certificate_oftp', 'OFTP'))),
        Item('log-forwarding', 'Log Forwarding', 'bi-arrow-right-circle',
             'Forward received logs to other destinations.',
             (('log_forward', 'Forwarders'),
              ('log_forward_service', 'Service'))),
        Item('log-fetching', 'Log Fetching', 'bi-cloud-download',
             'Fetch archived logs from another FortiAnalyzer.',
             (('log_fetch_client_profile', 'Client profiles'),
              ('log_fetch_server_settings', 'Server settings'))),
        Item('event-log', 'Event Log', 'bi-journal',
             'The unit\'s own event log is browsed in the GUI; local logging '
             'behaviour is configured under Device Logs and Miscellaneous.'),
        Item('task-monitor', 'Task Monitor', 'bi-list-task',
             'System tasks and their per-line progress.',
             (('task_task', 'Tasks'),)),
        Item('mail-server', 'Mail Server', 'bi-envelope',
             'SMTP servers used for alert email and report delivery.',
             (('system_mail_server', 'Mail servers'),)),
        Item('syslog-server', 'Syslog Server', 'bi-broadcast-pin',
             'Syslog destinations for local log forwarding.',
             (('system_syslog', 'Syslog servers'),)),
        Item('meta-fields', 'Meta Fields', 'bi-tags',
             'Custom metadata fields on administrator objects.',
             (('system_metadata_admins', 'Admin meta fields'),)),
        Item('device-logs', 'Device Logs', 'bi-hdd-stack',
             'Device log settings, rolling/upload and automatic deletion.',
             (('log_settings', 'Log settings'),
              ('system_auto_delete', 'Auto deletion'))),
        Item('admin', 'Admin', 'bi-person-badge',
             'Administrators, profiles, remote auth servers, global admin '
             'settings and the workflow approval matrix.',
             (('admin_user', 'Administrators'), ('admin_profile', 'Profiles'),
              ('admin_setting', 'Admin settings'), ('admin_ldap', 'LDAP'),
              ('admin_radius', 'RADIUS'), ('system_password_policy', 'Password policy'),
              ('system_saml', 'SAML SSO'),
              ('system_workflow_approval_matrix', 'Approval matrix'))),
        Item('ha', 'High Availability', 'bi-diagram-3',
             'FortiAnalyzer HA cluster members, roles and configuration sync status.',
             (('sys_ha_status', 'Live status'), ('system_ha', 'HA config'))),
        Item('storage-info', 'Storage Info', 'bi-device-hdd',
             'Disk allocation and per-ADOM analytics/archive quotas, plus the '
             'SQL database layout.',
             (('storage_info', 'ADOM storage'), ('sql_settings', 'SQL database'),
              ('sql_custom_index', 'Custom index'))),
        Item('misc', 'Miscellaneous Settings', 'bi-three-dots',
             'Global system settings: hostname/GUI, NTP, scheduled backup, '
             'SNMP and local log behaviour.',
             (('system_global', 'Global'), ('system_ntp', 'NTP'),
              ('system_backup_all_settings', 'Scheduled backup'),
              ('system_snmp_sysinfo', 'SNMP'),
              ('locallog_setting', 'Local log'))),
    )),
)


def menu():
    """The ordered tuple of FortiAnalyzer menu groups (= the real GUI panes)."""
    return _MENU


def find_item(key: str):
    """Return (group, item) for a leaf key, or None."""
    for g in _MENU:
        for it in g.items:
            if it.key == key:
                return g, it
    return None


# --------------------------------------------------------------------------- #
#  Per-ADOM menu visibility (admin-configurable, this FortiAnalyzer ADOM only).#
#  The hidden set is a JSON list of group/item keys stored in the replicated   #
#  ``app_settings`` table (Settings -> FAZ Menu). Filtering happens only in    #
#  the sidebar/index (``visible_menu``) and is guarded in ``faz.menu_page``;   #
#  ``menu()`` stays FULL so the SoT harvest (device_sync) keeps covering every #
#  section regardless of what the operator hides in the GUI.                   #
# --------------------------------------------------------------------------- #
_HIDDEN_KEY = 'faz.hidden_menu'


def all_keys() -> set:
    """Every valid group and item key — the allow-list for what may be hidden."""
    ks: set = set()
    for g in _MENU:
        ks.add(g.key)
        for it in g.items:
            ks.add(it.key)
    return ks


def hidden_keys() -> set:
    """The set of currently-hidden group/item keys (empty on any error)."""
    import json
    from ..models import AppSetting
    raw = AppSetting.get(_HIDDEN_KEY)
    if not raw:
        return set()
    try:
        val = json.loads(raw)
    except Exception:  # noqa: BLE001
        return set()
    if not isinstance(val, list):
        return set()
    valid = all_keys()
    return {k for k in val if k in valid}


def set_hidden_keys(keys) -> None:
    """Persist the hidden set (unknown keys are dropped)."""
    import json
    from ..models import AppSetting
    valid = all_keys()
    clean = sorted({str(k) for k in keys if str(k) in valid})
    AppSetting.set(_HIDDEN_KEY, json.dumps(clean))


def visible_menu(hidden: set | None = None):
    """The menu with hidden groups/items removed (cascade). A hidden group key
    drops the whole group; a group left with no visible items is dropped too."""
    if hidden is None:
        hidden = hidden_keys()
    if not hidden:
        return _MENU
    out = []
    for g in _MENU:
        if g.key in hidden:
            continue
        items = tuple(it for it in g.items if it.key not in hidden)
        if not items:
            continue
        out.append(Group(g.key, g.label, g.icon, items))
    return tuple(out)


def is_hidden(item_key: str, hidden: set | None = None) -> bool:
    """True if the leaf (or its parent group) is hidden — the URL guard."""
    if hidden is None:
        hidden = hidden_keys()
    if not hidden:
        return False
    found = find_item(item_key)
    if not found:
        return False
    g, it = found
    return g.key in hidden or it.key in hidden
