#!/usr/bin/env python3
"""Render ``CHANGELOG.md`` into a per-version Release notes section of the site.

WHY A GENERATOR AND NOT HAND-WRITTEN PAGES
------------------------------------------
``CHANGELOG.md`` is already the file the team edits, already ships in the
repository, and is already published whole as ``docs/changelog.html``. What it
could not do is answer "what shipped in 1.3.3?" without scrolling a thousand
lines. So this splits it — it does not restate it. Re-typing the entries as
per-version pages would create a second copy, and the second copy is the one
that goes stale in public.

Every fact on these pages is derived from the Markdown:

* the version list is the ``## [x.y.z]`` headings, in file order;
* the date is the heading's own date;
* the hub's teaser lines are the bold lead-ins of the section's own bullets;
* the "current release" badge comes from the repo-root ``VERSION`` file.

Nothing here is typed twice, so nothing here can disagree with the changelog.
``--check`` fails the suite when the pages no longer match, which is what makes
"edit the changelog, forget the site" impossible.

REDACTION IS NOT OPTIONAL
-------------------------
``site/`` is published to GitHub Pages. This reuses ``gen_site_docs``'s
``redact()``/``scan()`` pair and **aborts** on any survivor, naming pattern,
file and line — same fail-closed contract as the manual.
"""
from __future__ import annotations

import argparse
import json
import html
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import gen_site_docs as gsd  # noqa: E402

SITE = ROOT / "site"
OUT_DIR = SITE / "releases"
HUB = SITE / "releases.html"
CHANGELOG = ROOT / "CHANGELOG.md"
VERSION_FILE = ROOT / "VERSION"

GENERATED_NOTE = ("<!-- GENERATED by deploy/gen_release_notes.py "
                  "— do not edit; edit CHANGELOG.md -->")

#: ``## [1.3.5] - 2026-08-04``  or  ``## [Unreleased]``
HEADING = re.compile(r"^## \[([^\]]+)\](?:\s*-\s*(\S+))?\s*$", re.M)
#: a top-level entry — indented continuations and nested lists are not entries
ENTRY = re.compile(r"^- ", re.M)
#: the bold lead-in that opens most entries; may wrap across lines
LEAD_IN = re.compile(r"^- \*\*(.+?)\*\*", re.M | re.S)
SUBSECTION = re.compile(r"^### (.+?)\s*$", re.M)


def shipped_version() -> str:
    return VERSION_FILE.read_text(encoding="utf-8").strip()


def slug_for(version: str) -> str:
    """URL slug for a version heading.

    ``v`` prefix so the file never starts with a digit and the URL reads as a
    version rather than as a number that happens to have dots in it.
    """
    v = version.strip().lower()
    if v == "unreleased":
        return "unreleased"
    return "v" + re.sub(r"[^0-9a-z.\-]+", "-", v)


def title_for(version: str) -> str:
    if version.strip().lower() == "unreleased":
        return "Unreleased — the next release"
    return f"Version {version.strip()}"


#: inline Markdown markers that mean nothing once the text is plain.
#: NOT the underscore: in this changelog it is overwhelmingly snake_case --
#: stripping it turned `server_name` into "servername", which is a different
#: identifier and a wrong one. Emphasis in this file is written with asterisks.
INLINE_MARK = re.compile(r"[`*]")


def plain(text: str) -> str:
    """Collapse a Markdown fragment to plain prose.

    The teasers are rendered as escaped text, so a lead-in written
    ``**`server_name` and the SAN**`` would otherwise show its backticks. They
    are markup, not content.
    """
    return " ".join(INLINE_MARK.sub("", text).split()).rstrip(".")


def lead_ins(body: str, limit: int = 3) -> list[str]:
    out: list[str] = []
    for m in LEAD_IN.finditer(body):
        out.append(plain(m.group(1)))
        if len(out) >= limit:
            break
    return out


#: Keep a Changelog's closed vocabulary. Membership -- not length -- is what
#: separates a kind from a prose headline: "The manual rendered blank" is
#: twenty-five characters and is plainly not a kind, and a length threshold
#: read it as one.
KEEP_A_CHANGELOG_KINDS = frozenset(
    {"added", "changed", "deprecated", "removed", "fixed", "security"})


def kinds_of(body: str, limit: int = 4) -> list[str]:
    """The section's own sub-headings, de-duplicated in file order.

    Two shapes live in this changelog and they need different treatment. Older
    entries use Keep-a-Changelog kinds, and a version with three separate
    ``### Changed`` blocks was advertising "Changed \u00b7 Changed \u00b7 Changed" --
    a count of headings dressed up as a summary. Newer entries head each defect
    with a sentence, and one version's five sentences filled its whole card
    before the reader reached a single entry.

    So: the Keep-a-Changelog kinds, de-duplicated; and if a section has none, its
    FIRST headline alone. Never five.
    """
    seen: list[str] = []
    for name in SUBSECTION.findall(body):
        name = plain(name)
        if name not in seen:
            seen.append(name)
    kinds = [n for n in seen if n.lower() in KEEP_A_CHANGELOG_KINDS]
    if kinds:
        return kinds[:limit]
    return seen[:1]


def sections() -> list[dict]:
    text = CHANGELOG.read_text(encoding="utf-8")
    marks = list(HEADING.finditer(text))
    if not marks:
        raise SystemExit("error: CHANGELOG.md has no '## [version]' headings")
    out: list[dict] = []
    for i, m in enumerate(marks):
        end = marks[i + 1].start() if i + 1 < len(marks) else len(text)
        body = text[m.end():end].strip("\n")
        version = m.group(1).strip()
        out.append({
            "version": version,
            "date": (m.group(2) or "").strip(),
            "body": body,
            "slug": slug_for(version),
            "title": title_for(version),
            "kinds": kinds_of(body),
            "entries": len(ENTRY.findall(body)),
            "leads": lead_ins(body),
        })
    return out


def blurb_for(sec: dict) -> str:
    kinds = " · ".join(sec["kinds"]) or "Changes"
    n = sec["entries"]
    what = f"{n} entr{'y' if n == 1 else 'ies'}"
    if sec["slug"] == "unreleased":
        return f"Merged and not yet cut into a release — {kinds} · {what}."
    when = f" on {sec['date']}" if sec["date"] else ""
    return f"Released{when} — {kinds} · {what}."


def render_body(sec: dict) -> tuple[str, dict[str, str]]:
    """Render one changelog section, and map each heading to its anchor id.

    The id map is what lets a search hit deep-link into the right part of the
    right release. Recomputing the slug ourselves would be a second copy of the
    toc extension's algorithm, and the copy is the one that drifts.
    """
    import markdown as md_lib

    # Redact BEFORE rendering, so the placeholder flows into code blocks and
    # link text alike and there is no HTML-escaping seam to get wrong.
    raw = gsd.redact(sec["body"])
    md = md_lib.Markdown(extensions=gsd.MD_EXTENSIONS, output_format="html5")
    body = gsd.relink(md.convert(raw))

    def _flat(tokens):
        for t in tokens:
            yield t
            yield from _flat(t.get("children") or [])

    ids = {}
    for t in _flat(getattr(md, "toc_tokens", [])):
        if t.get("name") and t.get("level") in (2, 3):
            # unescape: the token is already HTML-escaped, but the key is
            # matched against a heading read straight out of the Markdown. A
            # heading containing "&" would never match and would lose its
            # anchor, so every hit under it would land at the top of the page.
            ids.setdefault(plain(html.unescape(t["name"])), t["id"])
    return body, ids


def entries_of(sec: dict, ids: dict[str, str]) -> list[dict]:
    """Every top-level changelog bullet of one section, as searchable records.

    Parsed from the Markdown rather than scraped back out of the rendered
    HTML: the text still knows which ``### kind`` heading a bullet sits under,
    and that is the one fact a result needs in order to say *where* in the
    release it lives.

    REDACTED FIRST. The rendered body goes through ``redact()`` on its way to
    the page, but this index is a SECOND path out of the same source, and the
    first version of it shipped three internal identifiers straight past that
    pass — caught only because ``scan()`` re-checks the output and aborts
    rather than warning. Every path out of the changelog redacts, or the one
    that does not is the leak.
    """
    out: list[dict] = []
    heading = ""
    cur: list[str] | None = None
    body = gsd.redact(sec["body"])

    def _flush() -> None:
        nonlocal cur
        if not cur:
            cur = None
            return
        raw = "\n".join(cur).strip()
        lead = LEAD_IN.match("- " + raw)
        text = plain(raw.replace("\n", " "))
        title = plain(lead.group(1)) if lead else text[:90]
        # The summary is what is left AFTER the title. Without this the two
        # fields are the same sentence twice for every entry that has no bold
        # lead-in, which is a result that fills two lines and says one thing.
        rest = text[len(title):] if text.startswith(title) else text
        out.append({
            "v": sec["version"], "s": sec["slug"], "d": sec["date"],
            "k": heading, "a": ids.get(heading, ""),
            "t": title,
            "x": rest.lstrip(" —-–:·,.").strip()[:280],
        })
        cur = None

    for line in body.splitlines():
        if line.startswith("### "):
            _flush()
            heading = plain(line[4:])
            continue
        if line.startswith("- "):
            _flush()
            cur = [line[2:]]
        elif cur is not None:
            if not line.strip():
                cur.append("")
            elif line.startswith((" ", "\t")):
                cur.append(line.strip())
            else:                       # unindented prose ends the bullet
                _flush()
    _flush()
    return out


def search_payload(records: list[dict]) -> str:
    """The cross-release search index, inlined as JSON.

    Inlined rather than fetched as a separate asset for two reasons: this site
    is published to a static host we do not configure, and — the one that
    matters — ``gsd.scan`` only sees what ``build()`` returns. An index emitted
    outside the build would bypass the leak scan that gates publication.
    """
    return json.dumps(records, ensure_ascii=False, separators=(",", ":")) \
        .replace("<", "\\u003c")


def version_menu(secs: list[dict], current: str, active: str,
                 prefix: str) -> str:
    """The left-hand version rail.

    ``prefix`` is ``releases/`` on the hub and empty on a version page, so each
    surface links correctly from where it sits. The hub's rail is also the
    ONLY place the hub may name a version page: the published guard asserts
    that ``href="releases/<slug>.html"`` appears exactly once per version and
    in changelog order, which is what stops a second link list from silently
    re-sorting the history.

    The current-release marker here is deliberately NOT the ``rel-badge
    rel-now`` markup used in a page header. That badge is the guard's evidence
    that exactly one page claims to be current; painting it into a rail that
    every page carries would make all seventeen of them claim it.
    """
    items = []
    for sec in secs:
        cls = "rel-nav-item" + (" is-active" if sec["slug"] == active else "")
        if sec["slug"] == "unreleased":
            tag = '<span class="rel-nav-tag rel-nav-next">next</span>'
        elif sec["version"] == current:
            tag = '<span class="rel-nav-tag rel-nav-cur">current</span>'
        else:
            tag = ""
        when = html.escape(sec["date"]) if sec["date"] else "unreleased"
        kinds = " · ".join(html.escape(k) for k in sec["kinds"]) or "Changes"
        n = sec["entries"]
        leads = "".join(f"<li>{html.escape(t)}</li>" for t in sec["leads"])
        more = n - len(sec["leads"])
        if more > 0:
            leads += f'<li class="rel-more">… and {more} more</li>'
        items.append(f"""      <a class="{cls}" href="{prefix}{sec["slug"]}.html" data-rel-version="{html.escape(sec["version"])}">
        <span class="rel-nav-head"><span class="rel-nav-v">{html.escape(sec["title"])}</span>{tag}</span>
        <span class="rel-nav-meta">{when} · {kinds} · {n} entr{"y" if n == 1 else "ies"}</span>
        <ul class="rel-leads">{leads}</ul>
      </a>""")
    return "\n".join(items)


def badge_for(sec: dict, current: str) -> str:
    """Which of the three states a section is in.

    One definition: the published guard proves that exactly one page wears the
    "current release" markup, and it can only stay true while one function
    decides it.
    """
    if sec["slug"] == "unreleased":
        return '<span class="rel-badge rel-next">not yet released</span>'
    if sec["version"] == current:
        return '<span class="rel-badge rel-now">current release</span>'
    return '<span class="rel-badge">superseded</span>'


def panel_head(sec: dict, current: str) -> str:
    badge = badge_for(sec, current)
    return f"""      <div class="rel-panel-head">
        <h2>{html.escape(sec["title"])} {badge}</h2>
        <p class="rel-meta">{html.escape(blurb_for(sec))}</p>
      </div>"""


def render_page(sec: dict, newer: dict | None, older: dict | None,
                current: str, secs: list[dict]) -> str:
    body, _ids = render_body(sec)

    nav = []
    if newer:
        nav.append(f'<a href="{newer["slug"]}.html">← {html.escape(newer["title"])}</a>')
    if older:
        nav.append(f'<a href="{older["slug"]}.html">{html.escape(older["title"])} →</a>')
    nav_html = ('<p class="rel-prevnext">' + " · ".join(nav) + "</p>") if nav else ""

    parts = [gsd.head(sec["title"], blurb_for(sec), "../", "releases.html",
                      body_class="wide")]
    parts.append(f"""
<header class="page wrap">
  <p class="eyebrow"><a href="../releases.html" style="color:inherit;text-decoration:none;">← Release notes</a></p>
  <h1>{html.escape(sec["title"])} {badge_for(sec, current)}</h1>
  <p class="sub">{html.escape(blurb_for(sec))}</p>
</header>

<section class="wrap">
  <div class="doc rel-doc">
    <aside class="toc rel-nav">
      <div class="toc-title">Releases</div>
      <form class="rel-nav-search" action="../releases.html" method="get" role="search">
        <input type="search" name="q" autocomplete="off" spellcheck="false"
               placeholder="Search all releases…" aria-label="Search all releases">
      </form>
{version_menu(secs, current, sec["slug"], "")}
    </aside>
    <div class="doc-body">
      <div class="mdx">
{body}
{nav_html}
      </div>
      <div class="callout" style="margin-top:24px;">
        <span class="cico">\U0001f5d2️</span>
        <p><b>Generated from the changelog.</b> This page is one section of
        <code>CHANGELOG.md</code>; the whole history in one page is the
        <a href="../docs/changelog.html">Changelog</a>. Internal addresses,
        hostnames and device names are replaced with <code>{{placeholders}}</code>.</p>
      </div>
    </div>
  </div>
</section>
""")
    parts.append(gsd.foot("../"))
    return "".join(parts)


def render_hub(secs: list[dict], current: str) -> str:
    """The releases landing page: version rail left, the changes right.

    The rail opens on the SHIPPED version rather than on the newest section,
    because "what is running on my node" is the question this page is opened
    with. An unreleased section that is merged but not cut is one click away
    and says so on its own badge.
    
    Not a ``.reveal`` section, unlike the manual. A reveal starts at opacity 0
    and waits for an intersection observer, and this section contains the
    search box and the whole version rail — the two controls the page exists
    for. Reference surfaces do not animate their own navigation.
    """
    landing = next((s for s in secs if s["version"] == current), secs[0])
    body, _ids = render_body(landing)

    records: list[dict] = []
    for sec in secs:
        _b, ids = render_body(sec)
        records.extend(entries_of(sec, ids))

    parts = [gsd.head(
        "Release notes",
        "Every SATOM release, newest first: what shipped, when, and why — "
        "one page per version, generated from the changelog.",
        "", "releases.html", body_class="wide")]
    parts.append(f"""
<header class="page wrap">
  <h1>Release <span class="grad">notes</span></h1>
  <p class="sub">Pick a version on the left; its changes are on the right. The
  shipped version is <b>v{html.escape(current)}</b>. Every entry here is a section of the
  project's <code>CHANGELOG.md</code> — the same file that ships in the repository and
  is readable on a node with <code>satom show docs</code>. The full history in a
  single page is the <a href="docs/changelog.html">Changelog</a>.</p>
</header>

<section class="wrap">
  <div class="doc rel-doc" id="relhub" data-rel-current="{html.escape(current)}">
    <aside class="toc rel-nav">
      <div class="toc-title">Releases <span class="rel-count">{len(secs)}</span></div>
      <div class="rel-nav-search sitesearch" data-search-scope="releases">
        <label class="ss-field">
          <span class="ss-ico" aria-hidden="true">🔍</span>
          <input type="search" id="relsearch-input" name="q" autocomplete="off" spellcheck="false"
                 placeholder="Search every release…" aria-label="Search every release"
                 aria-controls="relsearch-results">
          <button type="button" class="ss-clear" id="relsearch-clear" aria-label="Clear search" hidden>×</button>
        </label>
      </div>
{version_menu(secs, current, landing["slug"], "releases/")}
    </aside>
    <div class="doc-body">
      <div class="ss-results" id="relsearch-results" role="region" aria-live="polite" hidden></div>
      <div id="rel-panel">
{panel_head(landing, current)}
        <div class="mdx">
{body}
        </div>
      </div>
      <div class="callout" style="margin-top:24px;">
        <span class="cico">\U0001f5d2️</span>
        <p><b>Generated from the changelog.</b> Internal addresses, hostnames and
        device names are replaced with <code>{{placeholders}}</code>. Search covers
        every entry of every release; each result is labelled with the version it
        shipped in.</p>
      </div>
    </div>
  </div>
  <script type="application/json" id="relsearch-index">{search_payload(records)}</script>
</section>
""")
    parts.append(gsd.foot(""))
    return "".join(parts)


def build() -> dict[pathlib.Path, str]:
    secs = sections()
    current = shipped_version()
    out: dict[pathlib.Path, str] = {}
    for i, sec in enumerate(secs):
        newer = secs[i - 1] if i > 0 else None
        older = secs[i + 1] if i + 1 < len(secs) else None
        out[OUT_DIR / f"{sec['slug']}.html"] = render_page(
            sec, newer, older, current, secs)
    out[HUB] = render_hub(secs, current)
    return out


def _rel(path: pathlib.Path) -> str:
    """Display path. Falls back to absolute when the destination has been
    redirected outside the tree (the tests sandbox both ends), so a diagnostic
    helper can never be the thing that raises."""
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return str(path)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the published release notes are stale; write nothing")
    args = ap.parse_args(argv)

    pages = build()

    findings: list[str] = []
    for path, text in pages.items():
        findings.extend(gsd.scan(text, _rel(path)))
    if findings:
        print("ABORTED — internal identifiers survived redaction:", file=sys.stderr)
        for f in findings[:40]:
            print("  " + f, file=sys.stderr)
        return 1

    stale = [p for p, t in pages.items()
             if not p.is_file() or p.read_text(encoding="utf-8") != t]
    orphans = []
    if OUT_DIR.is_dir():
        orphans = [p for p in OUT_DIR.glob("*.html") if p not in pages]

    if args.check:
        if stale or orphans:
            print("published release notes are STALE:", file=sys.stderr)
            for p in stale + orphans:
                print("  " + _rel(p), file=sys.stderr)
            print("run: python3 deploy/gen_release_notes.py", file=sys.stderr)
            return 1
        print(f"published release notes are current ({len(pages)} pages)")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for path, text in pages.items():
        path.write_text(text, encoding="utf-8")
    for p in orphans:          # a version renamed in the changelog must not
        p.unlink()             # leave its old page serving forever
    print(f"wrote {len(pages)} pages ({len(stale)} changed, "
          f"{len(orphans)} removed), 0 leaks")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
