#!/usr/bin/env python3
"""Render the project manual from ``docs/*.md`` into the public site.

WHY A GENERATOR AND NOT HAND-WRITTEN PAGES
------------------------------------------
The manual already exists as Markdown in ``docs/`` and is what the team edits.
Re-typing it as HTML creates a second copy, and the second copy is the one that
goes stale in public. So the site pages are DERIVED, committed to git, and
``tests/test_docs_publication.py`` fails the suite if they no longer match the
Markdown. The site itself stays a plain static tree with no build step at serve
time — the reason ``site/README.md`` gives for having no Jekyll.

WHY REDACTION IS NOT OPTIONAL
-----------------------------
``site/`` is published to GitHub Pages by the production sync. Eleven of the
Markdown files carry real internal identifiers: RFC1918 addresses, ``.mx``
management hostnames, hypervisor names, node names, the backup server and an
administrator's e-mail. Publishing them verbatim is an inventory disclosure —
the exact class of leak the release pipeline's secret scan exists to stop.

Two passes, in this order:

1. ``redact()`` rewrites known internal identifiers to angle-bracket
   placeholders, so the published text still reads as documentation.
2. ``scan()`` re-checks the OUTPUT and **aborts the whole run** on any hit,
   naming pattern, file and line. It never warns and continues: a warning in a
   publication pipeline is a leak with a paper trail.

Device SHORT names (``fadc``, ``faz``, ``fortiweb``) are deliberately NOT
redacted — they are ADOM keys and URL segments of the product itself
(``/fadc/api/``), and rewriting them would mangle route documentation while
disclosing nothing: a label with no address is not an inventory.
"""
from __future__ import annotations

import argparse
import html
import pathlib
import re
import sys

ROOT_DIR = pathlib.Path(__file__).resolve().parents[1]

# Asset URLs carry a content hash (deploy/stamp_site_assets.py). The generator
# emits the same hash the curated pages carry — if it emitted the bare URL, the
# next regeneration would silently undo the stamping on 21 of the 27 pages.
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from stamp_site_assets import digest as _asset_digest  # noqa: E402
DOCS_DIR = ROOT_DIR / "docs"
SITE_DIR = ROOT_DIR / "site"
OUT_DIR = SITE_DIR / "docs"
HUB = SITE_DIR / "docs.html"

GENERATED_NOTE = "<!-- GENERATED by deploy/gen_site_docs.py — do not edit; edit docs/*.md -->"

# ---------------------------------------------------------------------------
# What gets published, in reading order, grouped for the hub page.
# A doc absent from this list is simply not published — that is the opt-in.
# ---------------------------------------------------------------------------
PAGES: list[tuple[str, str, str, str, str]] = [
    # (markdown file, output slug, title, icon, blurb)
    ("CHANGELOG.md", "changelog", "Changelog", "🗒️",
     "Every release and every change, newest first — the same file that ships in the repository and is readable inside the application."),
    ("management-overview.md", "management-overview", "Management overview", "🧭",
     "The system without jargon: what it solves, how mature it is, what it costs and what the risks are."),
    ("overview.md", "overview", "Project overview & operating rules", "📌",
     "What the platform is, how it is deployed, its security posture, and the rules the team works by."),
    ("user-guide.md", "user-guide", "User guide", "📖",
     "Day-to-day operation, screen by screen — the manual for someone using the web interface."),
    ("INSTALL.md", "install", "Installation & deployment", "📦",
     "Requirements, package lists per distribution, the preflight, clustering, hardening and uninstall."),
    ("cli.md", "cli", "Operator console (satom CLI)", "⌨️",
     "The command-line tool for a node whose web interface is down: diagnose, control, rebuild — and the sudo rule to request."),
    ("theming.md", "theming", "Theming the console", "🎨",
     "Design tokens, named themes, the value allowlist that keeps operator input out of the "
     "stylesheet's structure, the contrast audit and how to get back."),
    ("privilege-model.md", "privilege-model", "Privilege model & node trust", "🔐",
     "Which account runs what, the two-command sudo allowlist, the privileged-runner boundary and node-to-node trust."),
    ("safeguards.md", "safeguards", "Safeguards — full catalog", "🛡️",
     "Every protection: what it prevents, where it lives, and the command that proves it is armed."),
    ("git-backup-and-outage.md", "git-backup", "Git backup & surviving an outage", "🧯",
     "The anti-reset guard, the unpushed-commit alert, repository bundles and the four-copy recovery runbook."),
    ("encryption-and-node-tls.md", "encryption", "Encryption in transit & node TLS", "🔒",
     "Service certificates, node-to-node encryption, enforced database TLS and the live encryption probes."),
    ("acme-certificate-manager.md", "acme", "ACME / Let's Encrypt certificates", "📜",
     "Automated issuance, the DNS-provider catalog, and how credentials reach the signer without leaking."),
    ("api_v1.md", "api", "API v1 — integration manual", "🔌",
     "How a third party authenticates and drives the platform with a token."),
    ("engineering.md", "engineering", "Engineering manual", "🏗️",
     "Internal architecture for developers: layers, the endpoint registry, device clients, jobs and testing."),
    ("source-of-truth-spec.md", "source-of-truth", "Source-of-truth specification", "🗂️",
     "The authoritative behavioural specification for configuration harvesting and versioning."),
    ("release-pipeline.md", "release-pipeline", "Release & publication pipeline", "🚚",
     "How a release is sanitized, secret-scanned, audited and published."),
    ("release_notes.md", "release-notes", "Release notes & upgrade planning", "🗒️",
     "The known/resolved issue corpus behind the upgrade advisor."),
    ("server_policy.md", "server-policy", "Server policy reference", "🧱",
     "Field-level reference for the server policy object graph."),
    ("web_protection_profile.md", "web-protection-profile", "Web protection profile reference", "🧬",
     "The ~40 sub-policy WAF bundle, field by field."),
    ("wpp_exceptions.md", "wpp-exceptions", "WAF exceptions & signatures", "🩹",
     "Authoring and injecting WAF exceptions and signature carve-outs."),
    ("fortiadc.md", "fortiadc", "FortiADC — API conventions", "🧾",
     "REST conventions, object map and current coverage for FortiADC."),
]

GROUPS: list[tuple[str, str, list[str]]] = [
    ("Start here", "New to the platform — read these in order.",
     ["management-overview", "overview", "user-guide", "theming"]),
    ("Deploy & operate", "Getting it running, keeping it running, getting it back.",
     ["install", "cli", "privilege-model", "safeguards", "git-backup"]),
    ("Security", "Certificates, transport encryption and trust between nodes.",
     ["encryption", "acme"]),
    ("Build & integrate", "For developers extending the platform or driving it from outside.",
     ["api", "engineering", "source-of-truth", "release-pipeline", "release-notes"]),
    ("What changed", "Release history for the platform itself.",
     ["changelog"]),
    ("Device reference", "Field-level reference for the managed appliances.",
     ["server-policy", "web-protection-profile", "wpp-exceptions", "fortiadc"]),
]

# ---------------------------------------------------------------------------
# Redaction — ORDER MATTERS: specific identifiers before the generic patterns.
# ---------------------------------------------------------------------------
REDACTIONS: list[tuple[re.Pattern, str]] = [
    (re.compile(r"\bsatom-node-1\b|\bsatom-node-1\b"), "{primary-node}"),
    (re.compile(r"\bsatom-node-2\b|\bsatom-node-2\b"), "{standby-node}"),
    # Trailing [a-z0-9]* not + : a bare prefix ("satom-node") is still an
    # identifier, and requiring a suffix is the same anchoring mistake the
    # hostname rule made with wildcards. Caught on a LIVE served page.
    (re.compile(r"\bsatom-(?:mag|web)-[a-z0-9]*"), "{node}"),
    (re.compile(r"\bbackup-server(?:-[a-z0-9]+)?\b"), "{backup-server}"),
    (re.compile(r"\bfortiweb08\b|\bfaz01\b|\bfw[67]\b"), "{device}"),
    (re.compile(r"\bprt0\d\b"), "{hypervisor}"),
    # Anchored on the DOMAIN, not the leading label: real documentation writes
    # wildcard certs (*.example.net) and brace expansions (satom{,-2}.example.net),
    # neither of which starts with an alphanumeric. A label-anchored pattern
    # matched neither and the scanner caught all four occurrences.
    (re.compile(r"[A-Za-z0-9*{},._-]*\.visionebc\.mx\b"), "{host}.example.net"),
    # "192.0.2.248/.249" — a shorthand pair. The generic IP rule below rewrites
    # the first and leaves "/.249", which still discloses an octet.
    (re.compile(r"\b10\.\d{1,3}\.\d{1,3}\.\d{1,3}/\.\d{1,3}\b"), "<ip>/<ip>"),
    (re.compile(r"\b[A-Za-z0-9._%+-]+@(?:gmail|hotmail|outlook|yahoo)\.[A-Za-z]{2,}\b"),
     "{admin@example.net}"),
    (re.compile(r"\b10\.\d{1,3}\.\d{1,3}\.\d{1,3}\b"), "{ip}"),
    (re.compile(r"\b192\.168\.\d{1,3}\.\d{1,3}\b"), "{ip}"),
    (re.compile(r"\b172\.(?:1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3}\b"), "{ip}"),
]

# Re-checked against the OUTPUT. A hit aborts the run.
FORBIDDEN: list[tuple[str, re.Pattern]] = [
    ("rfc1918 address", re.compile(r"\b(?:10\.\d{1,3}|192\.168|172\.(?:1[6-9]|2\d|3[01]))\.\d{1,3}\.\d{1,3}\b")),
    ("internal hostname", re.compile(r"\.visionebc\.mx\b")),
    ("hypervisor name", re.compile(r"\bprt0\d\b")),
    ("node name", re.compile(r"\bsatom-(?:mag|web)-[a-z0-9]*")),
    ("backup server name", re.compile(r"\bbackup-server\b")),
    ("device instance name", re.compile(r"\bfortiweb08\b|\bfaz01\b")),
    ("personal e-mail", re.compile(r"[A-Za-z0-9._%+-]+@(?:gmail|hotmail|outlook|yahoo)\.")),
]


def redact(text: str) -> str:
    for pattern, replacement in REDACTIONS:
        text = pattern.sub(replacement, text)
    return text


def scan(text: str, where: str) -> list[str]:
    findings = []
    for lineno, line in enumerate(text.splitlines(), 1):
        for name, pattern in FORBIDDEN:
            m = pattern.search(line)
            if m:
                findings.append(f"{where}:{lineno}: {name}: {m.group(0)!r}")
    return findings


# ---------------------------------------------------------------------------
# Chrome — one definition, so a nav change lands on every generated page at once
# ---------------------------------------------------------------------------
NAV = [("index.html", "Home"), ("features.html", "Features"),
       ("architecture.html", "Architecture"), ("safeguards.html", "Safeguards"),
       ("docs.html", "Docs"), ("install.html", "Install")]

SOURCE_URL = "https://github.com/visionebc/SATOM"


def head(title: str, description: str, up: str, active: str) -> str:
    css_v = _asset_digest("site.css")
    js_v = _asset_digest("site.js")
    links = "\n".join(
        '        <a href="{}{}"{}>{}</a>'.format(
            up, href, ' class="active"' if href == active else "", label)
        for href, label in NAV)
    return f"""<!DOCTYPE html>
<html lang="en">
{GENERATED_NOTE}
<head>
<meta charset="UTF-8">
<script>(function(){{try{{var t=localStorage.getItem("satom.site.theme");if(t==="aurora"||t==="abyss"||t==="classic"){{document.documentElement.setAttribute("data-theme",t);}}}}catch(e){{}}}})();</script>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{html.escape(title)} — SATOM</title>
<meta name="description" content="{html.escape(description)}">
<link rel="icon" href="{up}favicon.ico" sizes="any">
<link rel="icon" type="image/png" href="{up}assets/favicon.png">
<link rel="apple-touch-icon" href="{up}assets/apple-touch-icon.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{up}assets/site.css?v={css_v}">
<script src="{up}assets/site.js?v={js_v}" defer></script>
</head>
<body>

<nav>
  <div class="wrap nav-inner">
    <a class="brand" href="{up}index.html"><img class="mark" src="{up}assets/satom-mark.png" alt="SATOM"> <span class="wordmark">SA<b>TOM</b></span></a>
    <button class="nav-toggle" id="nav-toggle" aria-label="Menu">☰</button>
    <div class="nav-right">
      <div class="nav-links">
{links}
      </div>
      <div class="theme-pick" role="group" aria-label="Colour theme">
        <button type="button" class="sw sw-aurora" data-theme-set="aurora" aria-pressed="true" title="Aurora — default" aria-label="Aurora theme"></button>
        <button type="button" class="sw sw-abyss" data-theme-set="abyss" aria-pressed="false" title="Abyss — dark" aria-label="Abyss dark theme"></button>
        <button type="button" class="sw sw-classic" data-theme-set="classic" aria-pressed="false" title="Classic" aria-label="Classic theme"></button>
      </div>
      <a class="nav-cta" href="{SOURCE_URL}">Source ↗</a>
    </div>
  </div>
</nav>
"""


def foot(up: str) -> str:
    links = "\n".join(f'      <a href="{up}{href}">{label}</a>' for href, label in NAV)
    return f"""
<footer>
  <div class="wrap">
    <div class="fbrand"><img src="{up}assets/visionebc-wordmark.png" alt="Vision EBC"></div>
    <div class="flinks">
{links}
      <a href="{SOURCE_URL}">Source</a>
    </div>
    <p class="addr">http://satom.visionebc.com</p>
    <p style="margin-top:8px;"><b>SATOM</b> · System Automation &amp; Task Orchestration Manager</p>
    <p style="margin-top:6px;">© <span class="year">2026</span> Vision EBC · Licensed under the <a href="{SOURCE_URL}/blob/main/LICENSE">Elastic License 2.0</a> · source-available, not OSI open source · provided AS IS, no warranty</p>
    <p class="disclaimer" style="margin-top:8px;font-size:12px;opacity:.6;line-height:1.5;">SATOM is an independent source-available project, <b>not affiliated with or endorsed by Fortinet, Inc.</b> Fortinet, FortiWeb, FortiADC and FortiAnalyzer are trademarks of Fortinet, Inc., used here nominatively to describe interoperability. SATOM is <b>not</b> a FortiManager or FortiGate product.</p>
  </div>
</footer>
<a id="top" href="#" aria-label="Back to top">↑</a>
</body>
</html>
"""


def source_for(md_name: str) -> pathlib.Path:
    """Where a published document actually lives.

    Most sit in ``docs/``. The changelog sits at the repo root because that
    is where every other tool looks for it (Keep a Changelog, the forge, the
    release pipeline); copying it into ``docs/`` would create a second copy
    that rots. One resolver so the presence check and the renderer cannot
    disagree about which files exist.
    """
    in_docs = DOCS_DIR / md_name
    return in_docs if in_docs.is_file() else ROOT_DIR / md_name


def render_doc(md_name: str, slug: str, title: str, icon: str, blurb: str) -> str:
    import markdown as md_lib

    source = source_for(md_name)
    raw = source.read_text(encoding="utf-8")
    # Redact BEFORE rendering: the placeholder then flows into code blocks and
    # link text alike, and there is no HTML-escaping seam to get wrong.
    raw = redact(raw)

    # No nl2br here, unlike the in-app renderer: these files are hard-wrapped at
    # ~90 columns, and nl2br would turn every wrap into a visible line break.
    md = md_lib.Markdown(extensions=["toc", "fenced_code", "tables", "sane_lists", "attr_list"],
                         output_format="html5")
    body = md.convert(raw)

    # toc_tokens is a TREE, not a list: the only top-level token is the H1, so
    # filtering it directly produced a one-entry table of contents. Flatten,
    # then keep h2 — the H1 is hidden in the page body anyway (the page header
    # already carries the title).
    def _flat(tokens):
        for t in tokens:
            yield t
            yield from _flat(t.get("children") or [])

    toc = [t for t in _flat(getattr(md, "toc_tokens", []))
           if t.get("name") and t.get("level") == 2]
    if not toc:  # a document written entirely with h1/h3 still gets a usable TOC
        toc = [t for t in _flat(getattr(md, "toc_tokens", []))
               if t.get("name") and t.get("level") in (1, 3)]
    toc_html = "\n".join(
        '      <a href="#{}">{}</a>'.format(html.escape(t["id"]), html.escape(t["name"]))
        for t in toc[:45])

    parts = [head(title, blurb, "../", "docs.html")]
    parts.append(f"""
<header class="page wrap">
  <p class="eyebrow"><a href="../docs.html" style="color:inherit;text-decoration:none;">← Documentation</a></p>
  <h1>{icon} {html.escape(title)}</h1>
  <p class="sub">{html.escape(blurb)}</p>
  <div class="callout" style="margin-top:18px;">
    <span class="cico">🕶️</span>
    <p><b>Published copy.</b> Internal addresses, hostnames and device names are replaced
    with <code>{{placeholders}}</code>. The unredacted original is <code>{html.escape(source.relative_to(ROOT_DIR).as_posix())}</code>
    in the repository and is rendered inside the application at <code>/docs</code>.</p>
  </div>
</header>

<section class="wrap reveal">
  <div class="doc">
    <aside class="toc">
      <div class="toc-title">On this page</div>
{toc_html}
    </aside>
    <div class="doc-body mdx">
{body}
    </div>
  </div>
</section>
""")
    parts.append(foot("../"))
    return "".join(parts)


def render_hub() -> str:
    by_slug = {slug: (icon, title, blurb) for _md, slug, title, icon, blurb in PAGES}
    parts = [head("Documentation",
                  "The complete SATOM manual: overview, user guide, installation, operator "
                  "console, privilege model, safeguards, API and device reference.",
                  "", "docs.html")]
    parts.append("""
<header class="page wrap">
  <h1>The <span class="grad">manual</span></h1>
  <p class="sub">Every document that ships with SATOM, in reading order. The same
  Markdown is rendered inside the application at <code>/docs</code> for signed-in
  users; the recovery procedures are also readable from the console itself with
  <code>satom show runbook</code>, on a node with no browser and no internet.</p>
</header>
""")
    for name, lead, slugs in GROUPS:
        cards = []
        for slug in slugs:
            icon, title, blurb = by_slug[slug]
            cards.append(
                f'    <div class="card"><div class="ico">{icon}</div>'
                f'<h3><a href="docs/{slug}.html">{html.escape(title)}</a></h3>'
                f'<p>{html.escape(blurb)}</p></div>')
        parts.append(f"""
<section class="wrap reveal">
  <div class="sec-head">
    <span class="eyebrow">{html.escape(name)}</span>
    <h2>{html.escape(lead)}</h2>
  </div>
  <div class="grid">
{chr(10).join(cards)}
  </div>
</section>
""")
    parts.append(foot(""))
    return "".join(parts)


def build() -> dict[pathlib.Path, str]:
    out: dict[pathlib.Path, str] = {}
    for md_name, slug, title, icon, blurb in PAGES:
        out[OUT_DIR / f"{slug}.html"] = render_doc(md_name, slug, title, icon, blurb)
    out[HUB] = render_hub()
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the published pages are stale; write nothing")
    args = ap.parse_args()

    missing = [m for m, *_ in PAGES if not source_for(m).is_file()]
    if missing:
        print("error: missing source documents: " + ", ".join(missing), file=sys.stderr)
        return 2

    pages = build()

    findings: list[str] = []
    for path, text in pages.items():
        findings.extend(scan(text, path.relative_to(ROOT_DIR).as_posix()))
    if findings:
        print("ABORTED — internal identifiers survived redaction:", file=sys.stderr)
        for f in findings[:40]:
            print("  " + f, file=sys.stderr)
        if len(findings) > 40:
            print(f"  … and {len(findings) - 40} more", file=sys.stderr)
        return 1

    stale = [p for p, t in pages.items()
             if not p.is_file() or p.read_text(encoding="utf-8") != t]
    if args.check:
        if stale:
            print("published documentation is STALE:", file=sys.stderr)
            for p in stale:
                print("  " + p.relative_to(ROOT_DIR).as_posix(), file=sys.stderr)
            print("run: python3 deploy/gen_site_docs.py", file=sys.stderr)
            return 1
        print(f"published documentation is current ({len(pages)} pages)")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for path, text in pages.items():
        path.write_text(text, encoding="utf-8")
    print(f"wrote {len(pages)} pages ({len(stale)} changed), 0 leaks")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
