#!/usr/bin/env python3
"""Render the project manual from ``docs/*.md`` into the public site.

WHY A GENERATOR AND NOT HAND-WRITTEN PAGES
------------------------------------------
The manual already exists as Markdown in ``docs/`` and is what the team edits.
Re-typing it as HTML creates a second copy, and the second copy is the one that
goes stale in public. So the site pages are DERIVED, committed to git, and
``tests/test_docs_publication.py`` fails the suite if they no longer match the
Markdown. The site itself stays a plain static tree with no build step at serve
time — the reason ``site/README.md`` gives for having no Jekyll.

WHY REDACTION IS NOT OPTIONAL
-----------------------------
``site/`` is published to GitHub Pages by the production sync. Eleven of the
Markdown files carry real internal identifiers: RFC1918 addresses, ``.mx``
management hostnames, hypervisor names, node names, the backup server and an
administrator's e-mail. Publishing them verbatim is an inventory disclosure —
the exact class of leak the release pipeline's secret scan exists to stop.

Two passes, in this order:

1. ``redact()`` rewrites known internal identifiers to angle-bracket
   placeholders, so the published text still reads as documentation.
2. ``scan()`` re-checks the OUTPUT and **aborts the whole run** on any hit,
   naming pattern, file and line. It never warns and continues: a warning in a
   publication pipeline is a leak with a paper trail.

Device SHORT names (``fadc``, ``faz``, ``fortiweb``) are deliberately NOT
redacted — they are ADOM keys and URL segments of the product itself
(``/fadc/api/``), and rewriting them would mangle route documentation while
disclosing nothing: a label with no address is not an inventory.
"""
from __future__ import annotations

import argparse
import html
import importlib.util
import json
import pathlib
import sys

ROOT_DIR = pathlib.Path(__file__).resolve().parents[1]

# Asset URLs carry a content hash (deploy/stamp_site_assets.py). The generator
# emits the same hash the curated pages carry — if it emitted the bare URL, the
# next regeneration would silently undo the stamping on 21 of the 27 pages.
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from stamp_site_assets import digest as _asset_digest  # noqa: E402
# The publishable registry AND the redaction table are shared verbatim with the
# application's unauthenticated /docs/public surface. They used to live here,
# so the application could not reuse them and grew its own public route that
# served a document unredacted. One registry, two published surfaces.
#
# Loaded by PATH, not as ``app.services.doc_publication``: importing the ``app``
# package would drag in Flask and the whole configuration layer, and the site
# build has to keep working on a tree whose application code does not compile.
_dp_spec = importlib.util.spec_from_file_location(
    "satom_doc_publication", ROOT_DIR / "app" / "services" / "doc_publication.py")
_dp = importlib.util.module_from_spec(_dp_spec)
_dp_spec.loader.exec_module(_dp)

DOCS_DIR = _dp.DOCS_DIR
PAGES = _dp.PUBLIC_DOCS
GROUPS = _dp.GROUPS
REDACTIONS = _dp.REDACTIONS
FORBIDDEN = _dp.FORBIDDEN
redact = _dp.redact
scan = _dp.scan
source_for = _dp.source_for
MD_EXTENSIONS = _dp.MD_EXTENSIONS
relink = _dp.relink

SITE_DIR = ROOT_DIR / "site"
OUT_DIR = SITE_DIR / "docs"
HUB = SITE_DIR / "docs.html"

GENERATED_NOTE = "<!-- GENERATED by deploy/gen_site_docs.py \u2014 do not edit; edit docs/*.md -->"


# ---------------------------------------------------------------------------
# Chrome — one definition, so a nav change lands on every generated page at once
# ---------------------------------------------------------------------------
NAV = [("index.html", "Home"), ("features.html", "Features"),
       ("architecture.html", "Architecture"), ("safeguards.html", "Safeguards"),
       ("docs.html", "Docs"), ("releases.html", "Releases"),
       ("docs/api.html", "API"), ("install.html", "Install")]

SOURCE_URL = "https://github.com/visionebc/SATOM"


def head(title: str, description: str, up: str, active: str,
         body_class: str = "") -> str:
    """The chrome every generated page gets.

    ``body_class`` widens the reading column. It is a BODY class rather than a
    per-element modifier because ``.wrap`` is used four times on a page (nav,
    header, content, footer) and a page whose nav is 1120px wide over content
    that is 1536px wide reads as a layout bug. One class, one decision.
    """
    css_v = _asset_digest("site.css")
    js_v = _asset_digest("site.js")
    links = "\n".join(
        '        <a href="{}{}"{}>{}</a>'.format(
            up, href, ' class="active"' if href == active else "", label)
        for href, label in NAV)
    return f"""<!DOCTYPE html>
<html lang="en">
{GENERATED_NOTE}
<head>
<meta charset="UTF-8">
<script>(function(){{var d=document.documentElement;d.className+=" js";setTimeout(function(){{if(!window.__satomReveal){{d.className=d.className.replace(" js","");}}}},2500);try{{var t=localStorage.getItem("satom.site.theme");if(t==="aurora"||t==="abyss"||t==="classic"){{document.documentElement.setAttribute("data-theme",t);}}}}catch(e){{}}}})();</script>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{html.escape(title)} — SATOM</title>
<meta name="description" content="{html.escape(description)}">
<link rel="icon" href="{up}favicon.ico" sizes="any">
<link rel="icon" type="image/png" href="{up}assets/favicon.png">
<link rel="apple-touch-icon" href="{up}assets/apple-touch-icon.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{up}assets/site.css?v={css_v}">
<script src="{up}assets/site.js?v={js_v}" defer></script>
</head>
<body{f' class="{body_class}"' if body_class else ""}>

<nav>
  <div class="wrap nav-inner">
    <a class="brand" href="{up}index.html"><img class="mark" src="{up}assets/satom-mark.png" alt="SATOM"> <span class="wordmark">SA<b>TOM</b></span></a>
    <button class="nav-toggle" id="nav-toggle" aria-label="Menu">☰</button>
    <div class="nav-right">
      <div class="nav-links">
{links}
      </div>
      <div class="theme-pick" role="group" aria-label="Colour theme">
        <button type="button" class="sw sw-aurora" data-theme-set="aurora" aria-pressed="true" title="Aurora — default" aria-label="Aurora theme"></button>
        <button type="button" class="sw sw-abyss" data-theme-set="abyss" aria-pressed="false" title="Abyss — dark" aria-label="Abyss dark theme"></button>
        <button type="button" class="sw sw-classic" data-theme-set="classic" aria-pressed="false" title="Classic" aria-label="Classic theme"></button>
      </div>
      <a class="nav-cta" href="{SOURCE_URL}">Source ↗</a>
    </div>
  </div>
</nav>
"""


def foot(up: str) -> str:
    links = "\n".join(f'      <a href="{up}{href}">{label}</a>' for href, label in NAV)
    return f"""
<footer>
  <div class="wrap">
    <div class="fbrand"><img src="{up}assets/visionebc-wordmark.png" alt="Vision EBC"></div>
    <div class="flinks">
{links}
      <a href="{SOURCE_URL}">Source</a>
    </div>
    <p class="addr">https://satom.visionebc.com</p>
    <p style="margin-top:8px;"><b>SATOM</b> · System Automation &amp; Task Orchestration Manager</p>
    <p style="margin-top:6px;">© <span class="year">2026</span> Vision EBC · Licensed under the <a href="{SOURCE_URL}/blob/main/LICENSE">Elastic License 2.0</a> · source-available, not OSI open source · provided AS IS, no warranty</p>
    <p class="disclaimer" style="margin-top:8px;font-size:12px;opacity:.6;line-height:1.5;">SATOM is an independent source-available project, <b>not affiliated with or endorsed by Fortinet, Inc.</b> Fortinet, FortiWeb, FortiADC and FortiAnalyzer are trademarks of Fortinet, Inc., used here nominatively to describe interoperability. SATOM is <b>not</b> a FortiManager or FortiGate product.</p>
  </div>
</footer>
<a id="top" href="#" aria-label="Back to top">↑</a>
</body>
</html>
"""


def render_doc(md_name: str, slug: str, title: str, icon: str,
               blurb: str) -> tuple[str, list[dict]]:
    """Render one manual page.

    Returns the page AND its headings, because the hub's search index is built
    from the same render. Deriving the index from a second pass would be a
    second copy of the parse, and the copy is the one that rots.
    """
    import markdown as md_lib

    source = source_for(md_name)
    raw = source.read_text(encoding="utf-8")
    # Redact BEFORE rendering: the placeholder then flows into code blocks and
    # link text alike, and there is no HTML-escaping seam to get wrong.
    raw = redact(raw)

    # No nl2br here, unlike the in-app renderer: these files are hard-wrapped at
    # ~90 columns, and nl2br would turn every wrap into a visible line break.
    md = md_lib.Markdown(extensions=MD_EXTENSIONS, output_format="html5")
    body = md.convert(raw)
    # Inter-document links are written as Markdown-to-Markdown in the repo and
    # would 404 on the published site; rewrite them to the published slugs.
    body = relink(body)

    # toc_tokens is a TREE, not a list: the only top-level token is the H1, so
    # filtering it directly produced a one-entry table of contents. Flatten,
    # then keep h2 — the H1 is hidden in the page body anyway (the page header
    # already carries the title).
    def _flat(tokens):
        for t in tokens:
            yield t
            yield from _flat(t.get("children") or [])

    toc = [t for t in _flat(getattr(md, "toc_tokens", []))
           if t.get("name") and t.get("level") == 2]
    if not toc:  # a document written entirely with h1/h3 still gets a usable TOC
        toc = [t for t in _flat(getattr(md, "toc_tokens", []))
               if t.get("name") and t.get("level") in (1, 3)]
    # unescape FIRST: markdown's toc tokens carry the heading already
    # HTML-escaped, so escaping again shipped "Backups &amp;amp; restore" to
    # every sidebar. It only shows on a heading containing & < > or ", which is
    # why it survived this long.
    toc_html = "\n".join(
        '      <a href="#{}">{}</a>'.format(html.escape(t["id"]),
                                            html.escape(html.unescape(t["name"])))
        for t in toc[:45])

    # The search index carries h2 AND h3: half of what an operator looks for is
    # a numbered subsection ("10.1 Trust store", "14.10 Thresholds"), and an
    # index that only knew top-level headings would send them to a 1200-line
    # page and leave them to scroll.
    headings = [{"id": t["id"], "text": html.unescape(t["name"]),
                 "level": t["level"]}
                for t in _flat(getattr(md, "toc_tokens", []))
                if t.get("name") and t.get("level") in (2, 3)]

    parts = [head(title, blurb, "../", "docs.html", body_class="wide")]
    parts.append(f"""
<header class="page wrap">
  <p class="eyebrow"><a href="../docs.html" style="color:inherit;text-decoration:none;">← Documentation</a></p>
  <h1>{icon} {html.escape(title)}</h1>
  <p class="sub">{html.escape(blurb)}</p>
  <div class="callout" style="margin-top:18px;">
    <span class="cico">🕶️</span>
    <p><b>Published copy.</b> Internal addresses, hostnames and device names are replaced
    with <code>{{placeholders}}</code>. The unredacted original is <code>{html.escape(source.relative_to(ROOT_DIR).as_posix())}</code>
    in the repository, and is readable on the appliance itself with
    <code>satom show docs</code>.</p>
  </div>
</header>

<section class="wrap reveal">
  <div class="doc">
    <aside class="toc">
      <div class="toc-title">On this page</div>
{toc_html}
    </aside>
    <div class="doc-body mdx">
{body}
    </div>
  </div>
</section>
""")
    parts.append(foot("../"))
    return "".join(parts), headings


def _search_index(headings_by_slug: dict[str, list[dict]]) -> str:
    """The manual's client-side search index, inlined as JSON.

    Inlined rather than fetched: this site is published to a static host with no
    configuration of ours, and a search that needs a second request is a search
    that is broken by the first CDN hiccup or file:// preview. It is also the
    only shape the publication leak scan can see — ``scan()`` runs over the page
    text, so an index emitted as a separate asset would bypass it entirely.
    """
    group_of = {slug: name for name, _lead, slugs in GROUPS for slug in slugs}
    docs = []
    for _md, slug, title, icon, blurb in PAGES:
        docs.append({
            "s": slug, "t": title, "i": icon, "b": blurb,
            "g": group_of.get(slug, ""),
            "h": [{"a": h["id"], "t": h["text"], "l": h["level"]}
                  for h in headings_by_slug.get(slug, [])],
        })
    # `</script>` inside a JSON string would close the block early; escaping the
    # angle bracket is the standard fix and keeps the payload valid JSON.
    return json.dumps(docs, ensure_ascii=False, separators=(",", ":")) \
        .replace("<", "\\u003c")


def render_hub(headings_by_slug: dict[str, list[dict]] | None = None) -> str:
    by_slug = {slug: (icon, title, blurb) for _md, slug, title, icon, blurb in PAGES}
    parts = [head("Documentation",
                  "The complete SATOM manual: overview, user guide, installation, operator "
                  "console, privilege model, safeguards, API and device reference.",
                  "", "docs.html", body_class="wide")]
    parts.append("""
<header class="page wrap">
  <h1>The <span class="grad">manual</span></h1>
  <p class="sub">Every document that ships with SATOM, in reading order. The same
  Markdown is rendered inside the application at <code>/docs</code> for signed-in
  users; the recovery procedures are also readable from the console itself with
  <code>satom show runbook</code>, on a node with no browser and no internet.</p>
</header>
""")
    # Deliberately NOT inside a `.reveal` section: the reveal animation starts a
    # block at opacity 0 and waits for an observer. A search box that is
    # invisible until you scroll past it is a search box nobody finds.
    parts.append(f"""
<section class="wrap sitesearch" id="docsearch" data-search-scope="docs">
  <label class="ss-field">
    <span class="ss-ico" aria-hidden="true">🔍</span>
    <input type="search" id="docsearch-input" autocomplete="off" spellcheck="false"
           placeholder="Search the manual — try “trust store”, “threshold”, “ACME”, “provisioning”"
           aria-label="Search the manual" aria-controls="docsearch-results">
    <button type="button" class="ss-clear" id="docsearch-clear" aria-label="Clear search" hidden>×</button>
  </label>
  <p class="ss-hint" id="docsearch-hint">{len(PAGES)} documents · searches titles, summaries and every section heading</p>
  <div class="ss-results" id="docsearch-results" role="region" aria-live="polite" hidden></div>
  <script type="application/json" id="docsearch-index">{_search_index(headings_by_slug or {})}</script>
</section>
""")
    for name, lead, slugs in GROUPS:
        cards = []
        for slug in slugs:
            icon, title, blurb = by_slug[slug]
            cards.append(
                f'    <div class="card"><div class="ico">{icon}</div>'
                f'<h3><a href="docs/{slug}.html">{html.escape(title)}</a></h3>'
                f'<p>{html.escape(blurb)}</p></div>')
        parts.append(f"""
<section class="wrap reveal" data-search-hide>
  <div class="sec-head">
    <span class="eyebrow">{html.escape(name)}</span>
    <h2>{html.escape(lead)}</h2>
  </div>
  <div class="grid">
{chr(10).join(cards)}
  </div>
</section>
""")
    parts.append(foot(""))
    return "".join(parts)


def build() -> dict[pathlib.Path, str]:
    out: dict[pathlib.Path, str] = {}
    headings_by_slug: dict[str, list[dict]] = {}
    for md_name, slug, title, icon, blurb in PAGES:
        page, headings = render_doc(md_name, slug, title, icon, blurb)
        out[OUT_DIR / f"{slug}.html"] = page
        headings_by_slug[slug] = headings
    out[HUB] = render_hub(headings_by_slug)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the published pages are stale; write nothing")
    args = ap.parse_args()

    missing = [m for m, *_ in PAGES if not source_for(m).is_file()]
    if missing:
        print("error: missing source documents: " + ", ".join(missing), file=sys.stderr)
        return 2

    pages = build()

    findings: list[str] = []
    for path, text in pages.items():
        findings.extend(scan(text, path.relative_to(ROOT_DIR).as_posix()))
    if findings:
        print("ABORTED — internal identifiers survived redaction:", file=sys.stderr)
        for f in findings[:40]:
            print("  " + f, file=sys.stderr)
        if len(findings) > 40:
            print(f"  … and {len(findings) - 40} more", file=sys.stderr)
        return 1

    stale = [p for p, t in pages.items()
             if not p.is_file() or p.read_text(encoding="utf-8") != t]
    if args.check:
        if stale:
            print("published documentation is STALE:", file=sys.stderr)
            for p in stale:
                print("  " + p.relative_to(ROOT_DIR).as_posix(), file=sys.stderr)
            print("run: python3 deploy/gen_site_docs.py", file=sys.stderr)
            return 1
        print(f"published documentation is current ({len(pages)} pages)")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for path, text in pages.items():
        path.write_text(text, encoding="utf-8")
    print(f"wrote {len(pages)} pages ({len(stale)} changed), 0 leaks")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
