#!/usr/bin/env python3
"""Write the system-upgrade feed for one release into satom-system-upgrades/.

    gen_upgrade_feed.py <version> <sha256> <size> [--released YYYY-MM-DD]
                        [--repo visionebc/SATOM] [--dir satom-system-upgrades]
                        [--api-pack-sha256 SHA] [--knowledge-feed URL]

Writes ``satom-update-<version>.json`` (that release's entry), rewrites
``latest.json`` from the highest version present, and regenerates the version
table in ``README.md`` between its markers. Idempotent: running it twice for
the same release changes nothing.

The release pipeline runs it AFTER the update package is built and verified,
because the sha256 only exists then -- which is also why the feed is committed
after the release tag rather than inside it (the package contains the tree, so
the tree cannot contain the package's own hash).

The package itself is NOT stored here: it is a ~64 MB release asset, and a
folder of them in git would grow every clone by that much per release (and
GitHub refuses files over 100 MB). The feed points at the asset; the reader is
deploy/upgrade_feed.py.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import upgrade_feed  # noqa: E402  (same directory; stdlib only)

START = "<!-- versions:start (generated by deploy/gen_upgrade_feed.py) -->"
END = "<!-- versions:end -->"
KEY_NAME = "satom-release-2026.pub"
KEY_FINGERPRINT = "SHA256:cYv9NxiJjMn/K6srKxXg2kdvROP2g6fzgfMXU6sxPyA"


def _vkey(v: str):
    return tuple(int(x) if x.isdigit() else -1 for x in re.split(r"[.-]", v))


def entry(version, sha256, size, released, repo, api_pack=True, api_pack_sha256=None,
          knowledge_feed=None) -> dict:
    base = "https://github.com/%s/releases/download/v%s/" % (repo, version)
    name = "satom-update-%s.tar.gz" % version
    doc = {
        "schema": upgrade_feed.FEED_SCHEMA,
        "product": "satom",
        "version": version,
        "released": released,
        "release_url": "https://github.com/%s/releases/tag/v%s" % (repo, version),
        "package": {"name": name, "url": base + name, "sha256": sha256, "size": size},
        "signing_key": {"name": KEY_NAME, "fingerprint": KEY_FINGERPRINT,
                        "url": base + KEY_NAME},
    }
    if api_pack:
        doc["api_pack"] = {"name": "satom-apipack-%s.tar.gz" % version,
                           "url": base + "satom-apipack-%s.tar.gz" % version}
        # 3.0.0: the api_pack lane's sha256, so a node can check the asset it
        # downloads before the signature (same rule as the update package).
        if api_pack_sha256:
            doc["api_pack"]["sha256"] = api_pack_sha256.lower()
    # 3.0.0: where the rolling knowledge lane is published (its own latest.json).
    if knowledge_feed:
        doc["knowledge_feed"] = knowledge_feed
    # The reader's own validation, so the pipeline can never publish a feed
    # the nodes would refuse.
    upgrade_feed.parse_feed(json.dumps(doc).encode())
    return doc


def _dump(doc) -> str:
    return json.dumps(doc, indent=2, sort_keys=True) + "\n"


def write(out: Path, doc: dict) -> list:
    out.mkdir(parents=True, exist_ok=True)
    changed = []
    own = out / ("satom-update-%s.json" % doc["version"])
    if not own.exists() or own.read_text() != _dump(doc):
        own.write_text(_dump(doc))
        changed.append(own.name)

    entries = []
    for f in out.glob("satom-update-*.json"):
        entries.append(json.loads(f.read_text()))
    entries.sort(key=lambda d: _vkey(d["version"]), reverse=True)
    latest = out / "latest.json"
    if not latest.exists() or latest.read_text() != _dump(entries[0]):
        latest.write_text(_dump(entries[0]))
        changed.append(latest.name)

    readme = out / "README.md"
    text = readme.read_text() if readme.exists() else ""
    if START in text and END in text:
        rows = ["| Version | Released | Update package | sha256 | Size |",
                "|---------|----------|----------------|--------|------|"]
        for d in entries:
            p = d["package"]
            rows.append("| %s | %s | [%s](%s) | `%s` | %.1f MB |" % (
                d["version"], d.get("released") or "", p["name"], p["url"],
                p["sha256"], p["size"] / 1048576.0))
        head, rest = text.split(START, 1)
        tail = rest.split(END, 1)[1]
        new = head + START + "\n" + "\n".join(rows) + "\n" + END + tail
        if new != text:
            readme.write_text(new)
            changed.append(readme.name)
    return changed


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("version")
    ap.add_argument("sha256")
    ap.add_argument("size", type=int)
    ap.add_argument("--released", default=date.today().isoformat())
    ap.add_argument("--repo", default="visionebc/SATOM")
    ap.add_argument("--no-api-pack", action="store_true",
                    help="the release has no API pack asset (2.5.0 and older)")
    ap.add_argument("--api-pack-sha256", default=None,
                    help="sha256 of the release's api_pack asset (3.0.0+)")
    ap.add_argument("--knowledge-feed", default=None,
                    help="https URL of the knowledge lane's latest.json (3.0.0+)")
    ap.add_argument("--dir", default=str(Path(__file__).resolve().parents[1]
                                         / "satom-system-upgrades"))
    a = ap.parse_args(argv)
    try:
        doc = entry(a.version, a.sha256.lower(), a.size, a.released, a.repo,
                    api_pack=not a.no_api_pack, api_pack_sha256=a.api_pack_sha256,
                    knowledge_feed=a.knowledge_feed)
    except upgrade_feed.FeedError as exc:
        print("gen_upgrade_feed: refusing: %s" % exc, file=sys.stderr)
        return 2
    changed = write(Path(a.dir), doc)
    print("changed: %s" % (", ".join(changed) if changed else "nothing"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
