#!/usr/bin/env bash
# install.sh — deploy SATOM Web on the target LXC
set -euo pipefail

APP_DIR="/opt/satom"
LOG_DIR="/var/log/satom"
SERVICE_NAME="satom"

echo "==> Changing to application directory: $APP_DIR"
cd "$APP_DIR"

# 1. Create virtual environment
echo "==> Creating Python virtual environment"
python3 -m venv venv

# 2. Install Python dependencies
echo "==> Installing Python dependencies"
venv/bin/pip install --upgrade pip --quiet
venv/bin/pip install -r requirements.txt --quiet

# 3. Create required directories
echo "==> Creating data and log directories"
mkdir -p data "$LOG_DIR"

# 4. Generate .env if it does not already exist
if [ ! -f .env ]; then
    echo "==> Generating .env with secret keys"

    SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
    FERNET_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")

    cat > .env <<EOF
# Auto-generated by install.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
SECRET_KEY=${SECRET_KEY}
FERNET_KEY=${FERNET_KEY}
SQLALCHEMY_DATABASE_URI=sqlite:///$(pwd)/data/app.db
FLASK_ENV=production
EOF
    echo "    .env written."
else
    echo "==> .env already exists — skipping key generation"
fi

# 5. Initialise database and seed admin user
echo "==> Initialising database (create-db)"
FLASK_APP=wsgi.py venv/bin/flask create-db

# 6. Install and enable systemd service
echo "==> Installing systemd service"
cp deploy/satom.service /etc/systemd/system/"${SERVICE_NAME}".service
systemctl daemon-reload
systemctl enable "$SERVICE_NAME"
systemctl restart "$SERVICE_NAME"

# 7. TLS — every install shape serves HTTPS from its first boot.
#    Same provisioner as scripts/install.sh, installers/install-satom.sh and the
#    container stack, so the vhost cannot drift between install paths.
echo "==> Provisioning TLS (internal CA + node certificate + nginx)"
command -v nginx >/dev/null || { echo "installing nginx"; apt-get install -y -qq nginx >/dev/null; }
SERVED_NAMES="${SERVED_NAMES:-$(hostname -f 2>/dev/null || hostname)}"
NODE_IP="${NODE_IP:-$(hostname -I 2>/dev/null | awk '{print $1}')}"
APP_DIR="$APP_DIR" SATOM_SERVED_NAMES="$SERVED_NAMES" SATOM_NODE_IP="$NODE_IP" \
  "$APP_DIR/deploy/tls-bootstrap.sh" ensure-pki
APP_DIR="$APP_DIR" SATOM_SERVED_NAMES="$SERVED_NAMES" SATOM_NODE_IP="$NODE_IP" \
  "$APP_DIR/deploy/tls-bootstrap.sh" write-vhost \
    --out /etc/nginx/conf.d/satom.conf --port 443 --upstream 127.0.0.1:8000
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl enable nginx >/dev/null 2>&1 || true
systemctl reload nginx 2>/dev/null || systemctl restart nginx

echo ""
echo "Installation complete."
echo "App running at https://${SERVED_NAMES%% *}/  (self-signed — replace it with"
echo "  $APP_DIR/deploy/tls-bootstrap.sh import-cert --cert F --key F)"
echo "Service status: $(systemctl is-active $SERVICE_NAME)"
