#!/usr/bin/env bash
# install.sh — deploy Fortinet Manager Web on the target LXC
set -euo pipefail

APP_DIR="/opt/fortinet-manager"
LOG_DIR="/var/log/fortinet-manager"
SERVICE_NAME="fortinet-manager"

echo "==> Changing to application directory: $APP_DIR"
cd "$APP_DIR"

# 1. Create virtual environment
echo "==> Creating Python virtual environment"
python3 -m venv venv

# 2. Install Python dependencies
echo "==> Installing Python dependencies"
venv/bin/pip install --upgrade pip --quiet
venv/bin/pip install -r requirements.txt --quiet

# 3. Create required directories
echo "==> Creating data and log directories"
mkdir -p data "$LOG_DIR"

# 4. Generate .env if it does not already exist
if [ ! -f .env ]; then
    echo "==> Generating .env with secret keys"

    SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
    FERNET_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")

    cat > .env <<EOF
# Auto-generated by install.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
SECRET_KEY=${SECRET_KEY}
FERNET_KEY=${FERNET_KEY}
SQLALCHEMY_DATABASE_URI=sqlite:///$(pwd)/data/app.db
FLASK_ENV=production
EOF
    echo "    .env written."
else
    echo "==> .env already exists — skipping key generation"
fi

# 5. Initialise database and seed admin user
echo "==> Initialising database (create-db)"
FLASK_APP=wsgi.py venv/bin/flask create-db

# 6. Install and enable systemd service
echo "==> Installing systemd service"
cp deploy/fortinet-manager.service /etc/systemd/system/"${SERVICE_NAME}".service
systemctl daemon-reload
systemctl enable "$SERVICE_NAME"
systemctl restart "$SERVICE_NAME"

echo ""
echo "Installation complete."
echo "App running at http://localhost:8000"
echo "Service status: $(systemctl is-active $SERVICE_NAME)"
