"""device_cache_tables

Revision ID: 6a13b09b7e79
Revises: ae0c4a5637e6
Create Date: 2026-06-29 17:23:06.295524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a13b09b7e79'
down_revision = 'ae0c4a5637e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_locks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('appliance_id', sa.Integer(), nullable=False),
    sa.Column('resource_key', sa.String(length=256), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('owner_label', sa.String(length=64), nullable=True),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appliance_id', 'resource_key', name='uq_resource_lock_dev_key')
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('appliance_id', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=64), nullable=True),
    sa.Column('trigger', sa.String(length=24), nullable=True),
    sa.Column('user_label', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('changed', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_runs_appliance_id'), ['appliance_id'], unique=False)

    op.create_table('device_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('appliance_id', sa.Integer(), nullable=False),
    sa.Column('layer', sa.String(length=16), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('blob_hash', sa.String(length=64), nullable=True),
    sa.Column('object_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appliance_id'], ['appliances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_snapshots_appliance_id'), ['appliance_id'], unique=False)
        batch_op.create_index('ix_device_snapshots_dev_section', ['appliance_id', 'section'], unique=False)

    op.create_table('device_objects',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('appliance_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('parent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('layer', sa.String(length=16), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('logical_name', sa.String(length=128), nullable=False),
    sa.Column('urn', sa.String(length=256), nullable=True),
    sa.Column('mkey', sa.String(length=256), nullable=True),
    sa.Column('subtable', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appliance_id'], ['appliances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['device_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['device_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_objects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_objects_appliance_id'), ['appliance_id'], unique=False)
        batch_op.create_index('ix_device_objects_dev_logical_mkey', ['appliance_id', 'logical_name', 'mkey'], unique=False)
        batch_op.create_index('ix_device_objects_dev_section', ['appliance_id', 'section'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_objects_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_objects_section'), ['section'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_objects_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('device_server_policies',
    sa.Column('object_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('appliance_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('deployment_mode', sa.String(length=64), nullable=True),
    sa.Column('vserver', sa.String(length=256), nullable=True),
    sa.Column('server_pool', sa.String(length=256), nullable=True),
    sa.Column('web_protection_profile', sa.String(length=256), nullable=True),
    sa.Column('http_service', sa.String(length=64), nullable=True),
    sa.Column('https_service', sa.String(length=64), nullable=True),
    sa.Column('monitor_mode', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['device_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('object_id')
    )
    with op.batch_alter_table('device_server_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_server_policies_appliance_id'), ['appliance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_server_policies_name'), ['name'], unique=False)

    op.create_table('device_server_pools',
    sa.Column('object_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('appliance_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('protocol', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['device_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('object_id')
    )
    with op.batch_alter_table('device_server_pools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_server_pools_appliance_id'), ['appliance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_server_pools_name'), ['name'], unique=False)

    op.create_table('device_web_protection_profiles',
    sa.Column('object_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('appliance_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('signature_rule', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['device_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('object_id')
    )
    with op.batch_alter_table('device_web_protection_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_web_protection_profiles_appliance_id'), ['appliance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_web_protection_profiles_name'), ['name'], unique=False)

    # ### end Alembic commands ###


    # Fleet-wide JSONB search index (PostgreSQL only; SQLite tests skip it).
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.create_index("ix_device_objects_payload_gin", "device_objects",
                        ["payload"], postgresql_using="gin")


def downgrade():
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.drop_index("ix_device_objects_payload_gin", table_name="device_objects")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_web_protection_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_web_protection_profiles_name'))
        batch_op.drop_index(batch_op.f('ix_device_web_protection_profiles_appliance_id'))

    op.drop_table('device_web_protection_profiles')
    with op.batch_alter_table('device_server_pools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_server_pools_name'))
        batch_op.drop_index(batch_op.f('ix_device_server_pools_appliance_id'))

    op.drop_table('device_server_pools')
    with op.batch_alter_table('device_server_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_server_policies_name'))
        batch_op.drop_index(batch_op.f('ix_device_server_policies_appliance_id'))

    op.drop_table('device_server_policies')
    with op.batch_alter_table('device_objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_objects_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_device_objects_section'))
        batch_op.drop_index(batch_op.f('ix_device_objects_parent_id'))
        batch_op.drop_index('ix_device_objects_dev_section')
        batch_op.drop_index('ix_device_objects_dev_logical_mkey')
        batch_op.drop_index(batch_op.f('ix_device_objects_appliance_id'))

    op.drop_table('device_objects')
    with op.batch_alter_table('device_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_device_snapshots_dev_section')
        batch_op.drop_index(batch_op.f('ix_device_snapshots_appliance_id'))

    op.drop_table('device_snapshots')
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_runs_appliance_id'))

    op.drop_table('sync_runs')
    op.drop_table('resource_locks')
    # ### end Alembic commands ###
