"""baseline

Revision ID: ae0c4a5637e6
Revises: 
Create Date: 2026-06-29 17:11:36.856707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0c4a5637e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('appliances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('host', sa.String(length=253), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_enc', sa.Text(), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('vdom', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('zone', sa.String(length=128), nullable=True),
    sa.Column('line', sa.String(length=128), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=True),
    sa.Column('hw_type', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('datasheet_filename', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_status', sa.String(length=16), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appliances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appliances_name'), ['name'], unique=True)

    op.create_table('change_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('params', sa.Text(), nullable=False),
    sa.Column('device_ids', sa.Text(), nullable=False),
    sa.Column('policies', sa.Text(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('window_end', sa.DateTime(), nullable=True),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('rollback', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('notify_status', sa.String(length=16), nullable=False),
    sa.Column('notify_log', sa.Text(), nullable=True),
    sa.Column('scheduled_action_id', sa.Integer(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firmware_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('build', sa.String(length=32), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_name'), ['name'], unique=True)

    op.create_table('scheduled_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('targets', sa.Text(), nullable=False),
    sa.Column('params', sa.Text(), nullable=False),
    sa.Column('schedule_kind', sa.String(length=16), nullable=False),
    sa.Column('schedule', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('catch_up', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=32), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('running_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_action_next_run'), ['next_run'], unique=False)

    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('exceptions', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'name', 'version', name='uq_template_kind_name_version')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_templates_status'), ['status'], unique=False)

    op.create_table('appliance_interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appliance_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('if_type', sa.String(length=64), nullable=True),
    sa.Column('connected_to', sa.String(length=256), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appliance_id'], ['appliances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appliance_interfaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appliance_interfaces_appliance_id'), ['appliance_id'], unique=False)

    op.create_table('change_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appliance_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=256), nullable=False),
    sa.Column('mkey', sa.String(length=256), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('before', sa.Text(), nullable=True),
    sa.Column('after', sa.Text(), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appliance_id'], ['appliances.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_history_ts'), ['ts'], unique=False)

    op.create_table('change_request_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cr_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('by', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cr_id'], ['change_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_request_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_request_event_cr_id'), ['cr_id'], unique=False)

    op.create_table('scheduled_action_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['scheduled_action.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_action_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_action_run_action_id'), ['action_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('wpp_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appliance_id', sa.Integer(), nullable=True),
    sa.Column('wpp_mkey', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('exc_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appliance_id'], ['appliances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wpp_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wpp_exceptions_appliance_id'), ['appliance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wpp_exceptions_category'), ['category'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('user_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'key')
    )
    op.create_table('wpp_exception_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exception_id', sa.Integer(), nullable=False),
    sa.Column('server_policy', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['wpp_exceptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exception_id', 'server_policy', name='uq_wpp_exc_policy')
    )
    with op.batch_alter_table('wpp_exception_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wpp_exception_policies_exception_id'), ['exception_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wpp_exception_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wpp_exception_policies_exception_id'))

    op.drop_table('wpp_exception_policies')
    op.drop_table('user_settings')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('wpp_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wpp_exceptions_category'))
        batch_op.drop_index(batch_op.f('ix_wpp_exceptions_appliance_id'))

    op.drop_table('wpp_exceptions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_profile_id'))

    op.drop_table('users')
    with op.batch_alter_table('scheduled_action_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_action_run_action_id'))

    op.drop_table('scheduled_action_run')
    with op.batch_alter_table('change_request_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_request_event_cr_id'))

    op.drop_table('change_request_event')
    with op.batch_alter_table('change_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_history_ts'))

    op.drop_table('change_history')
    with op.batch_alter_table('appliance_interfaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appliance_interfaces_appliance_id'))

    op.drop_table('appliance_interfaces')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_status'))
        batch_op.drop_index(batch_op.f('ix_templates_kind'))

    op.drop_table('templates')
    with op.batch_alter_table('scheduled_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_action_next_run'))

    op.drop_table('scheduled_action')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_name'))

    op.drop_table('profiles')
    op.drop_table('firmware_images')
    op.drop_table('change_request')
    with op.batch_alter_table('appliances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appliances_name'))

    op.drop_table('appliances')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
