"""Embedded recovery runbooks. STDLIB ONLY — this is plain data.

They live INSIDE the CLI on purpose. The operator who needs them is looking at
a node whose web UI is down, on a management network with no internet, possibly
from a serial console. A runbook that lives in the wiki, in the repo's docs/
directory or on a public site is a runbook that is unavailable exactly when it
is needed. ``docs/cli.md`` points here rather than duplicating the text, so
there is one copy to keep true.

Each entry is (title, [lines]). Keep every command in them COPY-PASTEABLE.
"""

RUNBOOKS = {

"web-down": ("The web UI does not answer", [
    "Symptom: https://<node>/ times out, refuses, or returns 502.",
    "",
    "1. Is it the app or the front door?",
    "     satom get service status web",
    "     satom get service status nginx",
    "   nginx up + app down  -> 502. Both up -> look at the network/vhost.",
    "",
    "2. The unit says active but nothing answers. This is the common case:",
    "   gunicorn keeps the unit 'active' while its workers crash-loop.",
    "     satom diagnose python        <- import errors, broken venv",
    "     satom get log web 80",
    "   A module that only gets imported INSIDE a function can be broken",
    "   while the app still starts and /healthz still returns 200. That is",
    "   what `diagnose python` exists for.",
    "",
    "3. Reachable locally but not by hostname?",
    "     satom diagnose nginx",
    "   Watch for the vhost trap: satom-tls.conf must carry default_server on",
    "   :443. Without it satom-pages.conf wins by alphabetical order and the",
    "   application becomes unreachable by name while the site still serves.",
    "",
    "4. Restart, and let the CLI verify instead of trusting systemctl:",
    "     sudo satom execute restart web",
    "",
    "5. Still down: capture everything for the ticket before changing more.",
    "     sudo satom execute support bundle",
]),

"db-down": ("PostgreSQL is unreachable or read-only", [
    "     satom diagnose database",
    "",
    "* 'could not connect' -> is the engine up at all?",
    "      systemctl status postgresql",
    "  Do NOT restart postgresql from this CLI: it is shared state and the",
    "  standby streams from it. Know why before you touch it.",
    "",
    "* 'read-only' on a node you believe is the primary: you are on the",
    "  STANDBY. Check with  satom get node status  before writing anything.",
    "  Writes belong on the primary; streaming carries them to the replica.",
    "",
    "* Authentication failed: the app's own credentials come from .env",
    "  (0640 root:<service account>). If .env is unreadable to you, every",
    "  credential-backed check degrades — that is by design, not a fault.",
    "",
    "* Replication broken? The primary enforces mutual-CA TLS on the",
    "  replication line (hostssl + clientcert=verify-ca). A certificate that",
    "  expired on either side stops replication with an auth error, not a TLS",
    "  error. Check both:  satom diagnose certificate  on each node.",
]),

"cert-expired": ("The service certificate expired or will not renew", [
    "     satom get certificate status",
    "     satom diagnose certificate",
    "     satom get certificate list",
    "",
    "Which renewal path applies depends on where the cert came from:",
    "  source=issued   -> minted by this node's internal CA, auto-renewed by",
    "                     satom-cert-renew.timer at 03:30. Force it now:",
    "                       sudo satom execute cert renew",
    "  source=imported -> NOT auto-renewable here. The fleet wildcard is",
    "                     renewed on the edge and copied in. Expiry alerts",
    "                     only; renewal is a copy step, not a command.",
    "",
    "Only the PRIMARY holds the internal CA key. A standby cannot issue.",
    "",
    "Renewal failures are journalled per node at state/cert-renew.jsonl and",
    "shown at /cert-manager/renewals. A nightly failure is invisible in the",
    "web UI until the expiry mail fires, so read the journal:",
    "     satom diagnose certificate",
]),

"disk-full": ("The filesystem is filling up", [
    "     satom diagnose disk",
    "",
    "Known accumulators, in the order they usually bite:",
    "  data/tmp/            scratch from harvests and uploads. Nothing prunes",
    "                       it automatically. This is normally the big one.",
    "  data/jobs/           one JSON per background job, forever: jobs.prune()",
    "                       exists but has no caller.",
    "  data/system_backups/ pg_dump bundles (retention applies).",
    "  data/git-bundles/    git bundles, keep=7.",
    "  /var/log/satom/, journald.",
    "",
    "Reclaim, oldest-first, with an explicit confirmation:",
    "     sudo satom execute repair tmp --older-than 7 --yes",
    "     sudo satom execute repair jobs --yes",
    "",
    "Deletes belong on the PRIMARY. satom-ha-datasync pulls data/ with",
    "rsync --delete, so deleting on the standby is pointless: the next sync",
    "restores the files. Deleting on the primary removes them from both.",
    "",
    "A full disk corrupts Postgres before it corrupts anything else. If you",
    "are already at 100%, free space FIRST and diagnose afterwards.",
]),

"peer": ("The two nodes disagree, or data/ stopped replicating", [
    "     satom get node status",
    "     satom diagnose peer",
    "",
    "The standby PULLS: satom-ha-datasync.timer runs on the standby only and",
    "is inert on the primary by design. An 'inactive' datasync on a primary",
    "is correct, not a fault.",
    "",
    "Peer discovery compares LOCAL IPs against data/ha_nodes.json — not the",
    "hostname. If that file lists names that no longer exist, the loop used to",
    "fall back to nodes[0] and could rsync a node against itself.",
    "",
    "The rsync key is authorised on the primary with a forced command that",
    "only accepts 'rsync --server --sender' over data/ — it is structurally",
    "incapable of writing. If the standby authenticates but transfers nothing,",
    "suspect file ownership inside data/ before suspecting the key.",
    "",
    "After a promote you must authorise the reverse direction on the NEW",
    "primary, or the old one can never pull again:",
    "     sudo ./install-satom.sh --authorize-peer <ip> \"<pubkey>\"",
]),

"promote": ("Promote the standby to primary", [
    "Preconditions — check all three, in this order:",
    "     satom get node status         (this node must be role=standby)",
    "     satom diagnose database",
    "     satom diagnose peer",
    "",
    "     sudo satom execute promote --yes",
    "",
    "Afterwards, on the NEW primary:",
    "  1. Authorise the old node's key so it can pull data/ again",
    "       sudo ./install-satom.sh --authorize-peer <ip> \"<pubkey>\"",
    "  2. Confirm the scheduler now fires here and is idle over there —",
    "     scheduled actions are primary-only:",
    "       satom diagnose scheduler",
    "  3. Confirm the backup timers and metrics collection took over:",
    "       satom diagnose backup",
    "",
    "The internal CA key lives ONLY on the original primary. A promoted node",
    "cannot issue certificates until that material is moved deliberately.",
]),

"restore": ("Restore the database from a bundle", [
    "     satom get backup list",
    "",
    "Restore runs on the PRIMARY. The standby's Postgres is a read-only",
    "replica; restoring there is impossible and pointless — streaming carries",
    "the primary's restored state over by itself.",
    "",
    "     sudo satom execute restore db <file> --yes",
    "",
    "What that does, in order: dumps the CURRENT database first (so a bad",
    "restore is itself reversible), stops web + scheduler + reconciler,",
    "pg_restore --clean --if-exists, starts them again, then verifies",
    "/healthz. If pg_restore fails the services are started again anyway —",
    "you get told, you do not get left with a stopped node.",
    "",
    "Three copies exist by design: this node, the standby (data/ via rsync)",
    "and the external backup server. (A fourth, an hourly git publish of",
    "reports/, was retired 2026-08-05 when the SoT moved to the local",
    "versioned store — see data/sot and services.sot_store.)",
    "",
    "A BUNDLE ALONE DOES NOT RECOVER A TOTAL LOSS.",
    "",
    "Every credential in that dump — appliance passwords, the backup",
    "server's own SFTP password, the node identity key — is Fernet",
    "ciphertext, and FERNET_KEY lives in .env, which is in NO bundle. That",
    "is deliberate: bundles are retained, mirrored to the peer and pushed",
    "off-box, so one carrying that key would make every copy a total",
    "compromise. The cost is that somebody has to hold the key separately.",
    "",
    "     satom diagnose recovery",
    "",
    "tells you whether anybody does. If it says 'never', do this BEFORE you",
    "need it, not during the outage:",
    "",
    "     sudo satom execute export recovery-key --yes",
    "",
    "A restore compares the bundle's recorded key fingerprint against this",
    "node's and says so when they differ — so a restore under the wrong key",
    "is a named error, not a database whose every password fails to decrypt",
    "for no visible reason.",
]),

"update-stuck": ("An update stays 'queued' forever", [
    "     satom execute update status",
    "",
    "The web worker only ENQUEUES: it writes JSON into data/update-requests/",
    "and a 'queued' status into data/update-status/. A privileged runner does",
    "the real work: satom-updater.path watches the directory and starts",
    "satom-updater.service.",
    "",
    "If the .path unit is disabled, requests queue forever and NOTHING",
    "reports an error. That is the failure mode — not slowness:",
    "     satom get service status updater",
    "     sudo satom execute enable updater",
    "",
    "The .path unit must be enabled --now on BOTH nodes.",
    "",
    "Note also that the venv is per-node and is NOT in git; data/ replication",
    "does not carry it. A pip change applies only to the node you ran it on.",
]),

"fresh-install": ("A new node is up — what is NOT armed yet", [
    "     satom diagnose install",
    "",
    "The installer gives you code, units, TLS and a database. It does NOT",
    "give you the automated protections, because those are DATA and operator",
    "edits win over code defaults in this product. No ScheduledAction row is",
    "ever seeded. A fresh node therefore has:",
    "  * no source-of-truth refresh    (device_sync)",
    "  * no nightly SoT snapshot       (device_inspect)",
    "  * no database bundles           (system_backup)",
    "  * no git repository bundles     (git_bundle)",
    "  * no probe sweep                (deep_monitor)",
    "  * eight alert signals computed and delivered to NOBODY",
    "",
    "Arm the minimum set (prints the plan first; --yes applies it):",
    "     sudo satom execute seed actions",
    "     sudo satom execute seed actions --yes",
    "",
    "Then give the alerts somewhere to go — Settings -> Alerts needs a",
    "recipient and SMTP, or every signal is computed and discarded:",
    "     satom get alerts status",
]),

"locked-out": ("Nobody can log in to the web UI", [
    "     satom get user list",
    "",
    "Look for: is_active=false, a locked_until in the future, or an account",
    "whose auth_source is the external IdP while the IdP is down.",
    "",
    "     sudo satom execute admin unlock <username>",
    "     sudo satom execute admin reset-password <username>",
    "",
    "The password is asked for interactively and never appears in argv — an",
    "argument would land in your shell history and in the process list, where",
    "any local user can read it. Without a TTY a strong one is generated and",
    "printed once.",
    "",
    "If no local admin exists at all, create the seed admin the way the",
    "installer does:  venv/bin/flask create-db  (idempotent; it seeds the",
    "default admin only when the users table is empty).",
]),

"scheduler-idle": ("Nothing automated is running", [
    "     satom diagnose scheduler",
    "     satom get scheduler status",
    "",
    "Three distinct causes, in the order worth checking:",
    "",
    "1. The sidecar is up but wedged. satom-scheduler can sit 'active",
    "   (running)' with nothing but a sleep inside it — that happened when a",
    "   role probe using runuser started failing under a non-root unit. The",
    "   check compares the actual process, not the unit state.",
    "",
    "2. The sidecar runs code older than the tree. It has its OWN copy of the",
    "   application, so touching an action spec or a probe registry and",
    "   restarting only 'web' leaves it on the old code. The symptom is",
    "   pathognomonic: a manual run succeeds while the scheduled run fails.",
    "     satom diagnose code",
    "     sudo satom execute restart scheduler",
    "",
    "3. There is nothing to run. Scheduled actions are never seeded:",
    "     sudo satom execute seed actions",
    "",
    "Scheduled actions fire on the PRIMARY only. Idle on a standby is correct.",
]),

"device-unreachable": ("An appliance stopped syncing", [
    "     satom get device status",
    "",
    "Separate the two channels before concluding anything — they fail",
    "independently:",
    "  * REST/cmdb blocked by licensing answers HTTP 423 (errcode -20010) to",
    "    every configuration read, while SSH and the monitor/telemetry",
    "    endpoints keep working normally. The box is fine; the harvest is not.",
    "  * TLS verification against a self-signed appliance certificate kills",
    "    the call BEFORE authentication. An appliance that never once synced",
    "    since it was added is almost always verify_ssl=true on a self-signed",
    "    box. That is the first thing to check on a new device.",
    "  * Genuinely unreachable: no route, powered off.",
    "",
    "Park a box you know is down, so it stops failing the hourly sweep and",
    "stops mailing you about itself:",
    "     sudo satom execute maintenance <device> on",
    "",
    "Maintenance suppresses automatic runs and their alerts; a MANUAL run",
    "still reaches the device, because parking it is usually the prelude to",
    "working on it.",
]),

}

ORDER = ["web-down", "db-down", "scheduler-idle", "update-stuck", "cert-expired",
         "disk-full", "peer", "promote", "restore", "fresh-install",
         "locked-out", "device-unreachable"]
